# Generated by Django 5.2 on 2026-09-13 22:19

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("webshell", "0008_auto_20251012_1438"),
    ]

    operations = [
        migrations.CreateModel(
            name="SwarmNode",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=11,
                        max_length=255,
                        prefix="node_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hostname", models.CharField(unique=True)),
                ("swarm_node_id", models.CharField(unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[("MANAGER", "Manager"), ("WORKER", "Worker")]
                    ),
                ),
                ("private_ip", models.GenericIPAddressField()),
                ("public_ip", models.GenericIPAddressField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROVISIONING", "Provisioning"),
                            ("READY", "Ready"),
                            ("DOWN", "Down"),
                            ("DRAINED", "Drained"),
                            ("FAILED", "Failed"),
                        ]
                    ),
                ),
                ("last_status_update", models.DateTimeField(null=True)),
                ("docker_version", models.CharField()),
                ("is_build_server", models.BooleanField(default=False)),
                ("is_app_server", models.BooleanField(default=True)),
                ("is_initial_install_server", models.BooleanField(default=False)),
                ("ssh_user", models.CharField(default="root")),
                ("ssh_port", models.PositiveIntegerField(default=22)),
                ("cpus", models.PositiveIntegerField(null=True)),
                ("memory_bytes", models.BigIntegerField(null=True)),
                (
                    "ssh_key",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="webshell.sshkey",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
