# Generated by Django 5.2 on 2026-09-13 22:24

from django.db import migrations
from django.conf import settings
import docker
from django.utils import timezone
import requests


def insert_initial_swarm_server(apps, schema_editor):
    SwarmNode = apps.get_model("swarm", "SwarmNode")

    client = docker.from_env()

    info = client.info()

    swarm_node_id = info["Swarm"]["NodeID"]

    self_node = client.nodes.get(swarm_node_id)
    self_node.update(
        {
            "Availability": "active",
            "Role": "manager",
            "Labels": {
                "zane.app-server": "true",
                "zane.build-server": "true",
            },
        }
    )

    response = requests.get("https://ipinfo.io/ip")
    response.raise_for_status()

    node = SwarmNode(
        cpus=info["NCPU"],
        memory_bytes=info["MemTotal"],
        hostname=self_node.attrs["Description"]["Hostname"],
        private_ip=self_node.attrs["Status"]["Addr"],
        public_ip=response.text.strip(),
        swarm_node_id=swarm_node_id,
        role="MANAGER",
        status="READY",
        docker_version=info["ServerVersion"],
        is_build_server=True,
        is_initial_install_server=True,
        last_status_update=timezone.now(),
    )

    node.save()


def rollback_workspace_and_projects(apps, schema_editor):
    SwarmNode = apps.get_model("swarm", "SwarmNode")
    SwarmNode.objects.filter().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("swarm", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            insert_initial_swarm_server,
            reverse_code=rollback_workspace_and_projects,
        )
    ]
