# Generated by Django 5.2 on 2026-09-13 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0002_auto_20260913_2224"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swarmnode",
            name="ssh_port",
        ),
        migrations.RemoveField(
            model_name="swarmnode",
            name="ssh_user",
        ),
    ]
