# Generated by Django 5.2 on 2026-09-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0003_remove_swarmnode_ssh_port_remove_swarmnode_ssh_user"),
        ("webshell", "0009_sshkey_port"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="swarmnode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_initial_install_server", True)),
                fields=("is_initial_install_server",),
                name="unique_initial_install_server",
            ),
        ),
    ]
