# Generated by Django 5.2 on 2026-09-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0004_swarmnode_unique_initial_install_server"),
        ("webshell", "0009_sshkey_port"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swarmnode",
            name="ssh_key",
        ),
        migrations.AddField(
            model_name="swarmnode",
            name="ssh_keys",
            field=models.ManyToManyField(related_name="servers", to="webshell.sshkey"),
        ),
    ]
