# Generated by Django 5.2 on 2026-09-17 14:06

from django.db import migrations


def associate_all_ssh_keys_to_initial_server(apps, schema_editor):
    SwarmNode = apps.get_model("swarm", "SwarmNode")
    SSHKey = apps.get_model("webshell", "SSHKey")

    initial_server = SwarmNode.objects.filter(is_initial_install_server=True).get()
    initial_server.ssh_keys.add(*SSHKey.objects.all())


def remove_all_ssh_keys_from_initial_server(apps, schema_editor):
    SwarmNode = apps.get_model("swarm", "SwarmNode")
    initial_server = SwarmNode.objects.filter(is_initial_install_server=True).get()

    initial_server.ssh_keys.clear()


class Migration(migrations.Migration):
    dependencies = [
        ("swarm", "0005_remove_swarmnode_ssh_key_swarmnode_ssh_keys"),
    ]

    operations = [
        migrations.RunPython(
            associate_all_ssh_keys_to_initial_server,
            reverse_code=remove_all_ssh_keys_from_initial_server,
        )
    ]
