# Generated by Django 5.2 on 2026-09-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0006_auto_20260917_1406"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swarmnode",
            name="docker_version",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="swarmnode",
            name="hostname",
            field=models.CharField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="swarmnode",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROVISIONING", "Provisioning"),
                    ("READY", "Ready"),
                    ("DOWN", "Down"),
                    ("DRAINED", "Drained"),
                    ("FAILED", "Failed"),
                ],
                default="PROVISIONING",
            ),
        ),
        migrations.AlterField(
            model_name="swarmnode",
            name="swarm_node_id",
            field=models.CharField(null=True, unique=True),
        ),
    ]
