# Generated by Django 5.2 on 2026-09-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0007_alter_swarmnode_docker_version_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swarmnode",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("PROVISIONING", "Provisioning"),
                    ("READY", "Ready"),
                    ("DOWN", "Down"),
                    ("DRAINED", "Drained"),
                    ("FAILED", "Failed"),
                ],
                default="PROVISIONING",
            ),
        ),
    ]
