# Generated by Django 5.2 on 2026-09-22 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0008_alter_swarmnode_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swarmnode",
            name="public_ip",
        ),
    ]
