# Generated by Django 5.2 on 2026-09-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0010_alter_swarmnode_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swarmnode",
            name="private_ip",
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
