# Generated by Django 5.2 on 2026-09-23 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0011_alter_swarmnode_private_ip"),
    ]

    operations = [
        migrations.CreateModel(
            name="SSHKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.CharField(max_length=255)),
                ("public_key", models.TextField()),
                ("private_key", models.TextField()),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("fingerprint", models.CharField(default=None, null=True)),
                ("port", models.PositiveIntegerField(default=22)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="swarm.swarmnode",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
