# Generated by Django 5.2 on 2026-09-23 02:07

from django.db import migrations


def copy_ssh_keys_from_webshell(apps, schema_editor):
    SwarmNode = apps.get_model("swarm", "SwarmNode")
    LegacySSHKey = apps.get_model("webshell", "SSHKey")
    SSHKey = apps.get_model("swarm", "SSHKey")

    node = SwarmNode.objects.filter(is_initial_install_server=True).first()
    if node is None:
        return

    legacy_keys = list(LegacySSHKey.objects.all())
    if len(legacy_keys) == 0:
        return

    SSHKey.objects.bulk_create(
        [
            SSHKey(
                node_id=node.id,
                user=key.user,
                public_key=key.public_key,
                private_key=key.private_key,
                slug=key.slug,
                fingerprint=key.fingerprint,
                port=key.port,
            )
            for key in legacy_keys
        ]
    )

    for key in legacy_keys:
        SSHKey.objects.filter(id=key.id).update(
            created_at=key.created_at, updated_at=key.updated_at
        )


def delete_copied_ssh_keys(apps, schema_editor):
    SSHKey = apps.get_model("swarm", "SSHKey")
    SSHKey.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("swarm", "0012_sshkey"),
        ("webshell", "0009_sshkey_port"),
    ]

    operations = [
        migrations.RunPython(
            copy_ssh_keys_from_webshell,
            reverse_code=delete_copied_ssh_keys,
        ),
    ]
