# Generated by Django 5.2 on 2026-09-23 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0013_auto_20260923_0207"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swarmnode",
            name="ssh_keys",
        ),
        migrations.AlterField(
            model_name="sshkey",
            name="node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ssh_keys",
                to="swarm.swarmnode",
            ),
        ),
    ]
