# Generated by Django 5.2 on 2026-09-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0014_remove_swarmnode_ssh_keys_alter_sshkey_node"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sshkey",
            name="slug",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
