# Generated by Django 5.2 on 2026-09-23 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0015_alter_sshkey_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sshkey",
            old_name="slug",
            new_name="name",
        ),
    ]
