# Generated by Django 5.2 on 2026-09-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0016_rename_slug_sshkey_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sshkey",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
