# Generated by Django 5.2 on 2026-09-23 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0017_alter_sshkey_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sshkey",
            name="port",
        ),
        migrations.AddField(
            model_name="swarmnode",
            name="ssh_port",
            field=models.PositiveIntegerField(default=22),
        ),
    ]
