# Generated by Django 5.2 on 2026-09-23 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0018_remove_sshkey_port_swarmnode_ssh_port"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swarmnode",
            name="ssh_port",
            field=models.PositiveIntegerField(
                default=22,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
    ]
