# Generated by Django 5.2 on 2026-09-24 18:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0019_alter_swarmnode_ssh_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="swarmnode",
            name="cluster_roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("BUILD_SERVER", "Build Server"),
                        ("APP_SERVER", "App Server"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
