# Generated by Django 5.2 on 2026-09-24 18:16

from django.db import migrations


def fill_in_cluster_roles(apps, schema_editor):
    SwarmNode = apps.get_model("swarm", "SwarmNode")

    for node in SwarmNode.objects.all():
        role_list = []
        if node.is_app_server:
            role_list.append("APP_SERVER")
        if node.is_build_server:
            role_list.append("BUILD_SERVER")
        node.cluster_roles = list(set(role_list))
        node.save()


def remove_cluster_roles(apps, schema_editor):
    SwarmNode = apps.get_model("swarm", "SwarmNode")
    SwarmNode.objects.update(cluster_roles=[])


class Migration(migrations.Migration):
    dependencies = [
        ("swarm", "0020_swarmnode_cluster_roles"),
    ]

    operations = [
        migrations.RunPython(
            fill_in_cluster_roles,
            reverse_code=remove_cluster_roles,
        )
    ]
