# Generated by Django 5.2 on 2026-09-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0021_auto_20260924_1816"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="swarmnode",
            name="is_app_server",
        ),
        migrations.RemoveField(
            model_name="swarmnode",
            name="is_build_server",
        ),
    ]
