# Generated by Django 5.2 on 2026-09-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0022_remove_swarmnode_is_app_server_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="swarmnode",
            old_name="role",
            new_name="swarm_role",
        ),
    ]
