# Generated by Django 5.2 on 2026-09-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0023_rename_role_swarmnode_swarm_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swarmnode",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("PROVISIONING", "Provisioning"),
                    ("READY", "Ready"),
                    ("DOWN", "Down"),
                    ("DRAINED", "Drained"),
                    ("FAILED", "Failed"),
                    ("REMOVED", "Removed"),
                ],
                default="CREATED",
            ),
        ),
    ]
