# Generated by Django 5.2 on 2026-09-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swarm", "0024_alter_swarmnode_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="swarmnode",
            name="services",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="swarmnode",
            name="status_message",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="swarmnode",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("PROVISIONING", "Provisioning"),
                    ("ACTIVE", "Active"),
                    ("DOWN", "Down"),
                    ("PAUSED", "Paused"),
                    ("DRAINED", "Drained"),
                    ("FAILED", "Failed"),
                    ("REMOVED", "Removed"),
                ],
                default="CREATED",
            ),
        ),
    ]
