# Generated by Django 5.2 on 2026-09-29 04:26

from django.db import migrations


def update_swarm_node_ready_status(apps, schema_editor):
    SwarmNode = apps.get_model("swarm", "SwarmNode")

    SwarmNode.objects.filter(status="READY").update(status="ACTIVE")


def back_port_node_status(apps, schema_editor):
    SwarmNode = apps.get_model("swarm", "SwarmNode")

    SwarmNode.objects.filter(status="ACTIVE").update(status="READY")


class Migration(migrations.Migration):
    dependencies = [
        ("swarm", "0025_swarmnode_services_swarmnode_status_message_and_more"),
    ]

    operations = [
        migrations.RunPython(
            update_swarm_node_ready_status,
            reverse_code=back_port_node_status,
        )
    ]
