# Generated by Django 5.2 on 2026-09-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0026_auto_20260929_0426"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swarmnode",
            name="last_status_update",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
