# Generated by Django 5.2 on 2026-10-06 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0027_alter_swarmnode_last_status_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="swarmnode",
            name="architecture",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="swarmnode",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("PROVISIONING", "Provisioning"),
                    ("FAILED", "Failed"),
                    ("REMOVED", "Removed"),
                    ("ACTIVE", "Active"),
                    ("DOWN", "Down"),
                    ("PAUSED", "Paused"),
                    ("DRAINED", "Drained"),
                ],
                default="CREATED",
            ),
        ),
    ]
