# Generated by Django 5.2 on 2026-10-06 00:36

from django.db import migrations
import docker
import json


def set_server_arch(apps, schema_editor):
    SwarmNode = apps.get_model("swarm", "SwarmNode")

    client = docker.from_env()

    nodes = client.nodes.list()

    node_map = {
        node.id: node.attrs["Description"]["Platform"]["Architecture"] for node in nodes
    }

    existing_servers = SwarmNode.objects.filter(
        swarm_node_id__in=[node.id for node in nodes]
    )

    for server in existing_servers:
        server.architecture = node_map[server.swarm_node_id]
        server.save()


def remove_server_arch(apps, schema_editor):
    SwarmNode = apps.get_model("swarm", "SwarmNode")
    SwarmNode.objects.filter().update(architecture=None)


class Migration(migrations.Migration):
    dependencies = [
        ("swarm", "0028_swarmnode_architecture_alter_swarmnode_status"),
    ]

    operations = [
        migrations.RunPython(
            set_server_arch,
            reverse_code=remove_server_arch,
        )
    ]
