# Generated by Django 5.2 on 2026-10-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swarm", "0029_auto_20261006_0036"),
    ]

    operations = [
        migrations.AlterField(
            model_name="swarmnode",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("PROVISIONING", "Provisioning"),
                    ("FAILED", "Failed"),
                    ("REMOVED", "Removed"),
                    ("ACTIVE", "Active"),
                    ("DOWN", "Down"),
                    ("UNHEALTHY", "Unhealthy"),
                    ("PAUSED", "Paused"),
                    ("DRAINED", "Drained"),
                ],
                default="CREATED",
            ),
        ),
    ]
