# Generated by Django 5.2 on 2026-06-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="license",
            name="uuid",
        ),
    ]
