# Generated by Django 5.2 on 2026-06-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0003_instancemeta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instancemeta",
            name="fingerprint",
            field=models.TextField(),
        ),
    ]
