# Generated by Django 5.2 on 2026-06-13 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0004_alter_instancemeta_fingerprint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="instancemeta",
            constraint=models.CheckConstraint(
                condition=models.Q(("id", 1)), name="instance_meta_singleton_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="license",
            constraint=models.CheckConstraint(
                condition=models.Q(("id", 1)), name="license_singleton_id"
            ),
        ),
    ]
