# Generated by Django 5.2 on 2026-06-26 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "system_cleanup_cron_schedule",
                    models.CharField(default="0 */4 * * *"),
                ),
                (
                    "metrics_cleanup_cron_schedule",
                    models.CharField(default="0 0 * * *"),
                ),
                (
                    "http_log_retention_days",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "build_cache_max_age_days",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "build_cache_max_use_space_bytes",
                    models.PositiveIntegerField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("cleanup_images", models.BooleanField(default=True)),
                ("cleanup_containers", models.BooleanField(default=True)),
                ("cleanup_volumes", models.BooleanField(default=True)),
                ("cleanup_networks", models.BooleanField(default=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)),
                        name="server_settings_singleton_id",
                    )
                ],
            },
        ),
    ]
