# Generated by Django 5.2 on 2026-06-26 21:49

from django.db import migrations


def create_system_settings_singleton(apps, schema_editor):
    SystemSettings = apps.get_model("console", "SystemSettings")
    SystemSettings.objects.create()


def delete_system_settings_singleton(apps, schema_editor):
    SystemSettings = apps.get_model("console", "SystemSettings")
    SystemSettings.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("console", "0002_systemsettings"),
    ]

    operations = [
        migrations.RunPython(
            create_system_settings_singleton,
            reverse_code=delete_system_settings_singleton,
        ),
    ]
