# Generated by Django 5.2 on 2026-07-02 03:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0003_auto_20260626_2149"),
    ]

    operations = [
        migrations.RenameField(
            model_name="systemsettings",
            old_name="metrics_cleanup_cron_schedule",
            new_name="app_data_cleanup_cron_schedule",
        ),
        migrations.RenameField(
            model_name="systemsettings",
            old_name="system_cleanup_cron_schedule",
            new_name="docker_system_prune_cron_schedule",
        ),
        migrations.RenameField(
            model_name="systemsettings",
            old_name="cleanup_containers",
            new_name="prune_containers",
        ),
        migrations.RenameField(
            model_name="systemsettings",
            old_name="cleanup_images",
            new_name="prune_images",
        ),
        migrations.RenameField(
            model_name="systemsettings",
            old_name="cleanup_networks",
            new_name="prune_networks",
        ),
        migrations.RenameField(
            model_name="systemsettings",
            old_name="cleanup_volumes",
            new_name="prune_volumes",
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="build_cache_max_age_days",
            field=models.PositiveIntegerField(
                default=30,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="build_cache_max_use_space_bytes",
            field=models.PositiveBigIntegerField(
                default=5368709120,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
