# Generated by Django 5.2 on 2026-06-26 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0003_auto_20260626_2149"),
    ]

    operations = [
        migrations.RenameField(
            model_name="systemsettings",
            old_name="system_cleanup_cron_schedule",
            new_name="docker_system_prune_cron_schedule",
        ),
        migrations.RenameField(
            model_name="systemsettings",
            old_name="cleanup_containers",
            new_name="prune_containers",
        ),
        migrations.RenameField(
            model_name="systemsettings",
            old_name="cleanup_images",
            new_name="prune_images",
        ),
        migrations.RenameField(
            model_name="systemsettings",
            old_name="cleanup_networks",
            new_name="prune_networks",
        ),
        migrations.RenameField(
            model_name="systemsettings",
            old_name="cleanup_volumes",
            new_name="prune_volumes",
        ),
    ]
