# Generated by Django 5.2 on 2026-08-02 15:05

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "console",
            "0004_rename_metrics_cleanup_cron_schedule_systemsettings_app_data_cleanup_cron_schedule_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomProxyConfig",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=11,
                        max_length=255,
                        prefix="prx_cfg_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("contents", models.TextField()),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ("-updated_at",),
            },
        ),
    ]
