# Generated by Django 5.2 on 2026-06-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "console",
            "0004_rename_system_cleanup_cron_schedule_systemsettings_docker_system_prune_cron_schedule_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="systemsettings",
            old_name="metrics_cleanup_cron_schedule",
            new_name="app_data_cleanup_cron_schedule",
        ),
    ]
