# Generated by Django 5.2 on 2026-07-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "console",
            "0005_rename_metrics_cleanup_cron_schedule_systemsettings_app_data_cleanup_cron_schedule",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="docker_build_cache_prune_cron_schedule",
            field=models.CharField(default="0 */4 * * *"),
        ),
    ]
