# Webapp based on caddy
FROM caddy:2.8-alpine

LABEL org.opencontainers.image.source=https://github.com/zane-ops/zane-ops

WORKDIR /var/www/html

COPY ./docs/dist/ ./docs
COPY ./openapi/schema.yml ./docs
COPY ./docs/Caddyfile /etc/caddy/Caddyfile