# Webapp based on caddy
FROM caddy:2.8-alpine

WORKDIR /var/www/html

ARG COMMIT_SHA
ENV COMMIT_SHA=$COMMIT_SHA

RUN apk update && apk add --no-cache curl

COPY ./frontend/dist/ .
COPY ./frontend/Caddyfile /etc/caddy/Caddyfile