FROM python:3.11.7
WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install uv
ENV VIRTUAL_ENV=/venv
RUN uv venv /venv
COPY requirements.txt requirements.txt
RUN uv pip install -r requirements.txt

COPY . /app

EXPOSE 8000

CMD /bin/bash -c "source /venv/bin/activate && python manage.py migrate && daphne -b 0.0.0.0 -p 8000 backend.asgi:application"