# grafana-provisioning/datasources/datasource.yaml
apiVersion: 1
datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://zane.loki:3100
    isDefault: true
    editable: true
  - name: Tempo
    type: tempo
    access: proxy
    url: http://zane.tempo:3200
    editable: true
