# Generated by Django 5.2 on 2026-06-12 19:36

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0002_remove_license_uuid"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstanceMeta",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "fingerprint",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None, length=32, max_length=255, prefix="ist_"
                    ),
                ),
            ],
        ),
    ]
