# Generated by Django 5.2 on 2025-12-30 19:28

import django.db.models.deletion
import shortuuid.django_fields
import zane_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("compose", "0001_initial"),
        ("compose", "0002_alter_composestack_id"),
        ("compose", "0003_alter_composestack_computed_compose_content_and_more"),
        ("compose", "0004_alter_composestack_stack_name_and_more"),
        ("compose", "0005_alter_composestack_id"),
        ("compose", "0006_remove_composestack_compose_com_stack_n_e59624_idx_and_more"),
        ("compose", "0007_add_alias_prefix_to_compose_stack"),
        ("compose", "0008_alter_composestack_alias_prefix"),
        ("compose", "0009_rename_alias_prefix_composestack_alias_suffix"),
        ("compose", "0010_remove_composestack_alias_suffix"),
        ("compose", "0011_composestack_urls"),
        ("compose", "0012_alter_composestackchange_field"),
    ]

    initial = True

    dependencies = [
        ("zane_api", "0312_service_zane_api_se_deploy__9e359b_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComposeStack",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=30,
                        max_length=255,
                        prefix="compose_stk_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=38)),
                (
                    "deploy_token",
                    models.CharField(max_length=35, null=True, unique=True),
                ),
                (
                    "user_compose_content",
                    models.TextField(help_text="Original YAML from user"),
                ),
                (
                    "computed_compose_content",
                    models.TextField(help_text="Processed YAML"),
                ),
                ("stack_name", models.CharField(max_length=255, null=True)),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compose_stacks",
                        to="zane_api.environment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compose_stacks",
                        to="zane_api.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ComposeStackDeployment",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hash",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=11,
                        max_length=255,
                        prefix="stk_dpl_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                            ("DEPLOYING", "Deploying"),
                            ("HEALTHY", "Healthy"),
                            ("UNHEALTHY", "Unhealthy"),
                            ("REMOVED", "Removed"),
                        ],
                        default="QUEUED",
                        max_length=10,
                    ),
                ),
                ("status_reason", models.TextField(blank=True, null=True)),
                ("service_statuses", models.JSONField(default=dict)),
                ("stack_snapshot", models.JSONField(null=True)),
                ("commit_message", models.TextField(default="update stack")),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "stack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="compose.composestack",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ComposeStackChange",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=11,
                        max_length=255,
                        prefix="stk_chg_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("compose_content", "Compose Content"),
                            ("env_overrides", "Env Overrides"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ADD", "Add"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        max_length=10,
                    ),
                ),
                ("item_id", models.CharField(max_length=255, null=True)),
                ("old_value", models.JSONField(null=True)),
                ("new_value", models.JSONField(null=True)),
                ("applied", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="compose.composestack",
                    ),
                ),
                (
                    "deployment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="compose.composestackdeployment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ComposeStackEnvOverride",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=255,
                        validators=[zane_api.validators.validate_env_name],
                    ),
                ),
                ("value", models.TextField(blank=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=11,
                        max_length=255,
                        prefix="stk_env_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="env_overrides",
                        to="compose.composestack",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="composestack",
            index=models.Index(fields=["slug"], name="compose_com_slug_ad0748_idx"),
        ),
        migrations.AddIndex(
            model_name="composestack",
            index=models.Index(
                fields=["deploy_token"], name="compose_com_deploy__33618c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="composestack",
            constraint=models.UniqueConstraint(
                fields=("slug", "project", "environment"),
                name="unique_compose_slug_per_env_and_project",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="composestackenvoverride",
            unique_together={("key", "stack")},
        ),
        migrations.AlterField(
            model_name="composestack",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=20,
                max_length=255,
                prefix="compose_stk_",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="composestack",
            name="computed_compose_content",
            field=models.TextField(help_text="Processed YAML", null=True),
        ),
        migrations.AlterField(
            model_name="composestack",
            name="user_compose_content",
            field=models.TextField(help_text="Original YAML from user", null=True),
        ),
        migrations.AlterField(
            model_name="composestack",
            name="stack_name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="composestack",
            index=models.Index(
                fields=["stack_name"], name="compose_com_stack_n_e59624_idx"
            ),
        ),
        migrations.AlterField(
            model_name="composestack",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=8,
                max_length=255,
                prefix="compose_stk_",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.RemoveIndex(
            model_name="composestack",
            name="compose_com_stack_n_e59624_idx",
        ),
        migrations.RemoveField(
            model_name="composestack",
            name="stack_name",
        ),
        migrations.AddField(
            model_name="composestack",
            name="urls",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="composestackchange",
            name="field",
            field=models.CharField(
                choices=[
                    ("compose_content", "Compose Content"),
                    ("env_overrides", "Env Overrides"),
                    ("urls", "Urls"),
                ],
                max_length=255,
            ),
        ),
    ]
