# Generated by Django 5.2 on 2025-12-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0002_alter_composestack_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composestack",
            name="computed_compose_content",
            field=models.TextField(help_text="Processed YAML", null=True),
        ),
        migrations.AlterField(
            model_name="composestack",
            name="user_compose_content",
            field=models.TextField(help_text="Original YAML from user", null=True),
        ),
    ]
