# Generated by Django 5.2 on 2025-12-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0003_alter_composestack_computed_compose_content_and_more"),
        ("zane_api", "0312_service_zane_api_se_deploy__9e359b_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composestack",
            name="stack_name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name="composestack",
            index=models.Index(
                fields=["stack_name"], name="compose_com_stack_n_e59624_idx"
            ),
        ),
    ]
