# Generated by Django 5.2 on 2025-12-29 17:45

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0004_alter_composestack_stack_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composestack",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=8,
                max_length=255,
                prefix="compose_stk_",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
