# Generated by Django 5.2 on 2025-12-29 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0005_alter_composestack_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="composestack",
            name="compose_com_stack_n_e59624_idx",
        ),
        migrations.RemoveField(
            model_name="composestack",
            name="stack_name",
        ),
    ]
