# Generated by Django 5.2 on 2025-12-29 18:04

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0006_remove_composestack_compose_com_stack_n_e59624_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="composestack",
            name="alias_prefix",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                editable=False,
                help_text="Stable prefix for network aliases, shared across environment clones",
                length=8,
                max_length=255,
                prefix="",
            ),
        ),
    ]
