# Generated by Django 5.2 on 2025-12-30 01:11

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0007_add_alias_prefix_to_compose_stack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composestack",
            name="alias_prefix",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefghijklmnopqrstuvwxyz0123456789",
                editable=False,
                help_text="Stable prefix for network aliases, shared across environment clones",
                length=8,
                max_length=255,
                prefix="",
            ),
        ),
    ]
