# Generated by Django 5.2 on 2025-12-30 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0008_alter_composestack_alias_prefix"),
    ]

    operations = [
        migrations.RenameField(
            model_name="composestack",
            old_name="alias_prefix",
            new_name="alias_suffix",
        ),
    ]
