# Generated by Django 5.2 on 2025-12-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0009_rename_alias_prefix_composestack_alias_suffix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="composestack",
            name="alias_suffix",
        ),
    ]
