# Generated by Django 5.2 on 2025-12-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0010_remove_composestack_alias_suffix"),
    ]

    operations = [
        migrations.AddField(
            model_name="composestack",
            name="urls",
            field=models.JSONField(null=True),
        ),
    ]
