# Generated by Django 5.2 on 2025-12-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0011_composestack_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composestackchange",
            name="field",
            field=models.CharField(
                choices=[
                    ("compose_content", "Compose Content"),
                    ("env_overrides", "Env Overrides"),
                    ("urls", "Urls"),
                ],
                max_length=255,
            ),
        ),
    ]
