# Generated by Django 5.2 on 2025-12-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compose", "0001_squashed_0012_alter_composestackchange_field"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="composestackenvoverride",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="composestackenvoverride",
            name="service",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="composestackenvoverride",
            unique_together={("key", "stack", "service")},
        ),
    ]
