# Generated by Django 5.2 on 2025-12-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0013_alter_composestackenvoverride_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composestackenvoverride",
            name="service",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
