# Generated by Django 5.2 on 2026-01-01 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0014_alter_composestackenvoverride_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="composestack",
            name="configs",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="composestackchange",
            name="field",
            field=models.CharField(
                choices=[
                    ("compose_content", "Compose Content"),
                    ("env_overrides", "Env Overrides"),
                    ("urls", "Urls"),
                    ("configs", "Configs"),
                ],
                max_length=255,
            ),
        ),
    ]
