# Generated by Django 5.2 on 2026-01-01 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0015_composestack_configs_alter_composestackchange_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="composestack",
            old_name="computed_compose_content",
            new_name="computed_content",
        ),
        migrations.RenameField(
            model_name="composestack",
            old_name="user_compose_content",
            new_name="user_content",
        ),
    ]
