# Generated by Django 5.2 on 2026-01-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "compose",
            "0016_rename_computed_compose_content_composestack_computed_content_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="composestack",
            name="configs",
            field=models.JSONField(null=True),
        ),
    ]
