# Generated by Django 5.2 on 2026-01-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0017_alter_composestack_configs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composestackchange",
            name="field",
            field=models.CharField(
                choices=[
                    ("compose_content", "Compose Content"),
                    ("env_overrides", "Env Overrides"),
                ],
                max_length=255,
            ),
        ),
    ]
