# Generated by Django 5.2 on 2026-01-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0018_alter_composestackchange_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="composestackdeployment",
            name="service_statuses",
        ),
        migrations.AddField(
            model_name="composestack",
            name="service_statuses",
            field=models.JSONField(default=dict),
        ),
    ]
