# Generated by Django 5.2 on 2026-01-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compose", "0019_remove_composestackdeployment_service_statuses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="composestack",
            name="network_alias_prefix",
            field=models.SlugField(max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="composestack",
            name="slug",
            field=models.SlugField(max_length=40),
        ),
    ]
