# Generated by Django 5.2 on 2026-01-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0020_composestack_network_alias_prefix_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composestackdeployment",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("CANCELLED", "Cancelled"),
                    ("DEPLOYING", "Deploying"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                    ("REMOVED", "Removed"),
                ],
                default="QUEUED",
                max_length=10,
            ),
        ),
    ]
