# Generated by Django 5.2 on 2026-01-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0021_alter_composestackdeployment_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="composestackenvoverride",
            unique_together={("key", "stack")},
        ),
        migrations.AlterField(
            model_name="composestackdeployment",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("CANCELLED", "Cancelled"),
                    ("DEPLOYING", "Deploying"),
                    ("FINISHED", "Finished"),
                    ("FAILED", "Failed"),
                    ("REMOVED", "Removed"),
                ],
                default="QUEUED",
                max_length=10,
            ),
        ),
        migrations.RemoveField(
            model_name="composestackenvoverride",
            name="service",
        ),
    ]
