# Generated by Django 5.2 on 2026-01-22 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0022_alter_composestackenvoverride_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="composestackdeployment",
            name="is_redeploy_of",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="compose.composestackdeployment",
            ),
        ),
        migrations.AlterField(
            model_name="composestackdeployment",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("DEPLOYING", "Deploying"),
                    ("FINISHED", "Finished"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="QUEUED",
                max_length=10,
            ),
        ),
    ]
