# Generated by Django 5.2 on 2026-02-01 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0023_composestackdeployment_is_redeploy_of_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComposeStackMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cpu_percent", models.FloatField()),
                ("memory_bytes", models.PositiveBigIntegerField()),
                ("net_tx_bytes", models.PositiveBigIntegerField()),
                ("net_rx_bytes", models.PositiveBigIntegerField()),
                ("disk_read_bytes", models.PositiveBigIntegerField()),
                ("disk_writes_bytes", models.PositiveBigIntegerField()),
                ("service_name", models.CharField()),
                (
                    "stack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="compose.composestack",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="compose_com_created_617a6c_idx"
                    ),
                    models.Index(
                        fields=["service_name"], name="compose_com_service_0595ed_idx"
                    ),
                ],
            },
        ),
    ]
