# Generated by Django 5.2 on 2026-02-01 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0024_composestackmetrics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composestackmetrics",
            name="stack",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metrics",
                to="compose.composestack",
            ),
        ),
    ]
