# Generated by Django 5.2 on 2026-02-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0025_alter_composestackmetrics_stack"),
    ]

    operations = [
        migrations.RenameField(
            model_name="composestack",
            old_name="service_statuses",
            new_name="services",
        ),
    ]
