# Generated by Django 5.2 on 2026-02-12 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0026_rename_service_statuses_composestack_services"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="composestackdeployment",
            options={"ordering": ["-queued_at"]},
        ),
    ]
