# Generated by Django 5.2 on 2026-02-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0027_alter_composestackdeployment_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="composestackdeployment",
            index=models.Index(
                fields=["queued_at"], name="compose_com_queued__233fc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="composestackdeployment",
            index=models.Index(fields=["status"], name="compose_com_status_145506_idx"),
        ),
    ]
