import createClient from "openapi-fetch";
import type { paths } from "./v1"; // generated by openapi-typescript

export const apiClient = createClient<paths>({
  baseUrl: import.meta.env.VITE_API_URL ?? "/api"
});
