FROM  fluentd:v1.16.2-1.1

LABEL org.opencontainers.image.source=https://github.com/zane-ops/zane-ops
LABEL org.opencontainers.image.description="Zaneops simple fluend wrapper"
LABEL org.opencontainers.image.licenses=MIT

COPY fluent.conf /fluentd/etc/