x-internal-envs: &internal-envs
  API_HOST: host.docker.internal:8000
  DJANGO_SECRET_KEY: 'django-insecure-^@$$8fc&u2j)4@k+p+bg0ei8sm+@+pwq)hstk$$a*0*7#k54kybx' # default value set in `settings.py`

services:
  zane-fluentd:
    image: fluentd:v1.16.2-1.1
    volumes:
      - "./fluentd/fluent.conf:/fluentd/etc/fluent.conf"
      - "$HOME/.fluentd/:/var/fluentd/"
    networks:
      zane:
        aliases:
          - zane.fluentd
    environment:
      <<: *internal-envs
    deploy:
      mode: global
  proxy:
    image: ghcr.io/fredkiss3/caddy-cloudflare:2.11.4-alpine
    command: caddy run  --resume  --config /etc/caddy/config.json 
    logging:
      driver: "fluentd"
      options:
        mode: "non-blocking"
        fluentd-address: "unix://$HOME/.fluentd/fluentd.sock"
        fluentd-async: "true"
        fluentd-max-retries: 10
        fluentd-sub-second-precision: "true"
        tag: '{"service_id":"zane.proxy"}'
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
      labels:
        zane.role: "proxy"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - "2019:2019"
    volumes:
      - ./proxy/default-caddy-config.json:/etc/caddy/config.json:ro
      - config-storage:/config
    environment:
      <<: *internal-envs
      CADDY_ADMIN: 0.0.0.0:2019
    networks:
      zane:
        aliases:
          - zane.proxy
  
  temporal-admin-tools:
    image: temporalio/admin-tools:1.24.2-tctl-1.18.1-cli-1.0.0
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=password
      - POSTGRES_SEEDS=zane.db
      - POSTGRES_SEEDS_CREATE=zane.db
      - SKIP_SCHEMA_SETUP=false
      - SKIP_DB_SETUP=false
      - SERVICES=history,matching,frontend,worker
      - TEMPORAL_HOME=/etc/temporal
      - TEMPORAL_ADDRESS=zane.temporal:7233
      - TEMPORAL_CLI_ADDRESS=zane.temporal:7233
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - BIND_ON_IP=0.0.0.0
    volumes:
      - "./temporalio/admin-tools-entrypoint.sh:/etc/temporal/setup.sh"
    entrypoint:
      - /etc/temporal/setup.sh
    deploy:
      mode: replicated-job
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.zane.main-server==true
    networks:
      - zane
volumes:
  # caddy-data:
  # caddy-config:
  config-storage:
networks:
  zane:
    external: true
