# Generated by Django 5.0.2 on 2024-02-19 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now),
        ),
    ]
