# Generated by Django 5.0.2 on 2024-02-19 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0004_alter_dockerregistryservice_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_production', models.BooleanField(default=True)),
                ('duration_in_ms', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ERROR', 'Error'), ('SUCCESS', 'Success'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zane_api.dockerregistryservice')),
            ],
            options={
                'unique_together': {('is_production', 'service')},
            },
        ),
        migrations.CreateModel(
            name='GitDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_production', models.BooleanField(default=True)),
                ('duration_in_ms', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ERROR', 'Error'), ('SUCCESS', 'Success'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('commit_hash', models.CharField(max_length=40)),
                ('commit_message', models.TextField(blank=True)),
                ('branch', models.CharField(max_length=255)),
                ('commit_author_username', models.CharField(max_length=255)),
                ('commit_author_avatar_url', models.URLField(null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zane_api.gitrepositoryservice')),
            ],
            options={
                'unique_together': {('is_production', 'service')},
            },
        ),
    ]
