# Generated by Django 5.0.2 on 2024-03-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0008_alter_project_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.PositiveIntegerField()),
                ('target', models.PositiveIntegerField(default=80)),
            ],
            options={
                'unique_together': {('source', 'target')},
            },
        ),
        migrations.AddField(
            model_name='dockerregistryservice',
            name='ports',
            field=models.ManyToManyField(to='zane_api.portmapping'),
        ),
        migrations.AddField(
            model_name='gitrepositoryservice',
            name='ports',
            field=models.ManyToManyField(to='zane_api.portmapping'),
        ),
    ]
