# Generated by Django 5.0.2 on 2024-03-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0009_portmapping_dockerregistryservice_ports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerregistryservice',
            name='docker_cmd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
