# Generated by Django 5.0.2 on 2024-03-09 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0010_volume_created_at_volume_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='size_limit',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1024)]),
        ),
    ]
