# Generated by Django 5.0.2 on 2024-03-14 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0011_alter_volume_size_limit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dockerdeployment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='gitdeployment',
            unique_together=set(),
        ),
    ]
