# Generated by Django 5.0.2 on 2024-03-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0012_alter_dockerdeployment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitdeployment',
            name='build_duration_in_ms',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
