# Generated by Django 5.0.2 on 2024-03-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0013_alter_gitdeployment_build_duration_in_ms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockerregistryservice',
            name='http_logs',
        ),
        migrations.RemoveField(
            model_name='gitrepositoryservice',
            name='http_logs',
        ),
        migrations.AddField(
            model_name='dockerdeployment',
            name='http_logs',
            field=models.ManyToManyField(to='zane_api.httplog'),
        ),
        migrations.AddField(
            model_name='gitdeployment',
            name='http_logs',
            field=models.ManyToManyField(to='zane_api.httplog'),
        ),
    ]
