# Generated by Django 5.0.2 on 2024-03-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0014_remove_dockerregistryservice_http_logs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='dockerService',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='gitService',
        ),
        migrations.AddField(
            model_name='dockerregistryservice',
            name='volumes',
            field=models.ManyToManyField(to='zane_api.volume'),
        ),
        migrations.AddField(
            model_name='gitrepositoryservice',
            name='volumes',
            field=models.ManyToManyField(to='zane_api.volume'),
        ),
    ]
