# Generated by Django 5.0.2 on 2024-03-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0015_remove_volume_dockerservice_remove_volume_gitservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.PositiveIntegerField(null=True, unique=True)),
                ('private', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='dockerregistryservice',
            name='port_config',
            field=models.ManyToManyField(to='zane_api.portconfiguration'),
        ),
        migrations.AddField(
            model_name='gitrepositoryservice',
            name='port_config',
            field=models.ManyToManyField(to='zane_api.portconfiguration'),
        ),
    ]
