# Generated by Django 5.0.2 on 2024-03-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0016_portconfiguration_dockerregistryservice_port_config_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dockerregistryservice',
            old_name='base_docker_image',
            new_name='image',
        ),
    ]
