# Generated by Django 5.0.2 on 2024-03-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('zane_api', '0019_portconfiguration_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portconfiguration',
            name='public',
            field=models.PositiveIntegerField(unique=True),
            preserve_default=False,
        ),
    ]
