# Generated by Django 5.0.2 on 2024-03-18 14:08

import zane_api.helpers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('zane_api', '0021_rename_private_portconfiguration_forwarded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerregistryservice',
            name='base_domain',
            field=models.CharField(blank=True, max_length=1000, null=True,
                                   validators=[zane_api.helpers.validate_url_domain]),
        ),
        migrations.AlterField(
            model_name='gitrepositoryservice',
            name='base_domain',
            field=models.CharField(blank=True, max_length=1000, null=True,
                                   validators=[zane_api.helpers.validate_url_domain]),
        ),
    ]
