# Generated by Django 5.0.2 on 2024-03-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0023_remove_dockerregistryservice_base_domain_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfigURL',
            new_name='URL',
        ),
    ]
