# Generated by Django 5.0.2 on 2024-03-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0024_rename_configurl_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockerregistryservice',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='gitrepositoryservice',
            name='base_url',
        ),
        migrations.AlterField(
            model_name='dockerregistryservice',
            name='additional_urls',
            field=models.ManyToManyField(to='zane_api.url'),
        ),
        migrations.AlterField(
            model_name='gitrepositoryservice',
            name='additional_urls',
            field=models.ManyToManyField(to='zane_api.url'),
        ),
    ]
