# Generated by Django 5.0.2 on 2024-03-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0026_rename_additional_urls_dockerregistryservice_urls_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portconfiguration',
            name='host',
            field=models.PositiveIntegerField(default=80, unique=True),
        ),
    ]
