# Generated by Django 5.0.2 on 2024-03-19 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0027_alter_portconfiguration_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dockerregistryservice',
            old_name='docker_credentials_email',
            new_name='docker_credentials_username',
        ),
    ]
