# Generated by Django 5.0.2 on 2024-03-19 05:56

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0028_rename_docker_credentials_email_dockerregistryservice_docker_credentials_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerdeployment',
            name='hash',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=11, max_length=11, prefix='', unique=True),
        ),
    ]
