# Generated by Django 5.0.2 on 2024-03-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0029_dockerdeployment_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dockerregistryservice',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='gitrepositoryservice',
            name='is_public',
        ),
    ]
