# Generated by Django 5.0.2 on 2024-03-20 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0030_remove_dockerregistryservice_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='size_limit',
        ),
    ]
