# Generated by Django 5.0.2 on 2024-03-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0031_remove_volume_size_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portconfiguration',
            name='host',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
