# Generated by Django 5.0.2 on 2024-03-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0032_alter_portconfiguration_host"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dockerdeployment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="gitdeployment",
            name="status",
        ),
        migrations.AddField(
            model_name="dockerdeployment",
            name="deployment_status",
            field=models.CharField(
                choices=[
                    ("OFFLINE", "Offline"),
                    ("ERROR", "Error"),
                    ("LIVE", "Live"),
                    ("PENDING", "Pending"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="gitdeployment",
            name="build_status",
            field=models.CharField(
                choices=[
                    ("ERROR", "Error"),
                    ("SUCCESS", "Success"),
                    ("PENDING", "Pending"),
                    ("QUEUED", "Queued"),
                ],
                default="QUEUED",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="gitdeployment",
            name="deployment_status",
            field=models.CharField(
                choices=[
                    ("OFFLINE", "Offline"),
                    ("ERROR", "Error"),
                    ("LIVE", "Live"),
                    ("PENDING", "Pending"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
