# Generated by Django 5.0.2 on 2024-03-22 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0033_remove_dockerdeployment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockerdeployment",
            name="is_redeploy_of",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zane_api.dockerdeployment",
            ),
        ),
        migrations.AddField(
            model_name="gitdeployment",
            name="is_redeploy_of",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zane_api.gitdeployment",
            ),
        ),
    ]
