# Generated by Django 5.0.2 on 2024-03-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0034_dockerdeployment_is_redeploy_of_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dockerregistryservice",
            name="env_variables",
        ),
        migrations.RemoveField(
            model_name="gitrepositoryservice",
            name="env_variables",
        ),
        migrations.AddField(
            model_name="dockerdeployment",
            name="env_variables",
            field=models.ManyToManyField(to="zane_api.envvariable"),
        ),
        migrations.AddField(
            model_name="gitdeployment",
            name="env_variables",
            field=models.ManyToManyField(to="zane_api.envvariable"),
        ),
    ]
