# Generated by Django 5.0.2 on 2024-03-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0035_remove_dockerregistryservice_env_variables_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portconfiguration",
            name="project",
        ),
        migrations.AlterField(
            model_name="gitrepositoryservice",
            name="dockerfile_path",
            field=models.CharField(default="./Dockerfile", max_length=255),
        ),
        migrations.AlterField(
            model_name="gitrepositoryworker",
            name="dockerfile_path",
            field=models.CharField(default="./Dockerfile", max_length=255),
        ),
    ]
