# Generated by Django 5.0.2 on 2024-03-26 05:40

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0036_remove_portconfiguration_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitdeployment",
            name="hash",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None, length=11, max_length=11, prefix="", unique=True
            ),
        ),
    ]
