# Generated by Django 5.0.2 on 2024-03-28 04:04

import zane_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0037_gitdeployment_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="base_path",
            field=models.CharField(
                default="/", validators=[zane_api.validators.validate_url_path]
            ),
        ),
    ]
