# Generated by Django 5.0.2 on 2024-03-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0038_alter_url_base_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dockerregistryservice",
            old_name="port_config",
            new_name="ports",
        ),
        migrations.RenameField(
            model_name="gitrepositoryservice",
            old_name="port_config",
            new_name="ports",
        ),
    ]
