# Generated by Django 5.0.2 on 2024-03-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0039_rename_port_config_dockerregistryservice_ports_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="strip_prefix",
            field=models.BooleanField(default=False),
        ),
    ]
