# Generated by Django 5.0.2 on 2024-03-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0040_url_strip_prefix"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="strip_prefix",
            field=models.BooleanField(default=True),
        ),
    ]
