# Generated by Django 5.0.2 on 2024-03-29 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0041_alter_url_strip_prefix"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="archived",
        ),
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
