# Generated by Django 5.0.2 on 2024-03-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0042_archivedproject_remove_project_archived_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="archivedproject",
            index=models.Index(fields=["slug"], name="zane_api_ar_slug_136301_idx"),
        ),
    ]
