# Generated by Django 5.0.2 on 2024-03-29 04:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0043_archivedproject_zane_api_ar_slug_136301_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["name"], name="zane_api_pr_name_b415df_idx"),
        ),
    ]
