# Generated by Django 5.0.2 on 2024-03-29 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0044_project_zane_api_pr_name_b415df_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="project",
            name="zane_api_pr_name_b415df_idx",
        ),
        migrations.RemoveField(
            model_name="project",
            name="name",
        ),
    ]
