# Generated by Django 5.0.2 on 2024-03-29 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0045_remove_project_zane_api_pr_name_b415df_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="archivedproject",
            old_name="created_at",
            new_name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="archivedproject",
            name="name",
        ),
        migrations.RemoveField(
            model_name="archivedproject",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="archivedproject",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
