# Generated by Django 5.0.2 on 2024-03-29 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0046_rename_created_at_archivedproject_deleted_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archivedproject",
            name="deleted_at",
        ),
        migrations.AddField(
            model_name="archivedproject",
            name="archived_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
