# Generated by Django 5.0.2 on 2024-03-29 07:18

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0047_remove_archivedproject_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=11,
                max_length=11,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
