# Generated by Django 5.0.2 on 2024-03-29 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0051_archivedproject_active_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archivedproject",
            name="active_project",
        ),
        migrations.AddField(
            model_name="archivedproject",
            name="active_version",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_version",
                to="zane_api.project",
            ),
        ),
    ]
