# Generated by Django 5.0.2 on 2024-03-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0052_remove_archivedproject_active_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedvolume",
            name="original_volume_id",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
