# Generated by Django 5.0.2 on 2024-03-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "zane_api",
            "0054_rename_original_volume_id_archivedvolume_original_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ArchivedDockerEnvVariables",
            new_name="ArchivedDockerEnvVariable",
        ),
    ]
