# Generated by Django 5.0.2 on 2024-03-31 17:47

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0056_alter_dockerdeployment_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockerdeployment",
            name="hash",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None, length=11, max_length=255, prefix="dpl_dkr_", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="dockerregistryservice",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=11,
                max_length=255,
                prefix="srv_dkr_",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="gitdeployment",
            name="hash",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None, length=11, max_length=255, prefix="dpl_git_", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="gitrepositoryservice",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=11,
                max_length=255,
                prefix="srv_git_",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=11,
                max_length=255,
                prefix="prj_",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=11,
                max_length=255,
                prefix="vol_",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
