# Generated by Django 5.0.2 on 2024-04-08 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0057_alter_dockerdeployment_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archiveddockerservice",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="docker_services",
                to="zane_api.archivedproject",
            ),
        ),
    ]
