# Generated by Django 5.0.2 on 2024-04-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0058_alter_archiveddockerservice_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockerdeployment",
            name="tag",
            field=models.CharField(
                blank=True, default="latest", max_length=255, null=True
            ),
        ),
    ]
