# Generated by Django 5.0.2 on 2024-04-24 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0059_dockerdeployment_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dockerregistryservice",
            old_name="image",
            new_name="image_repository",
        ),
    ]
