# Generated by Django 5.0.2 on 2024-04-24 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0061_rename_image_archiveddockerservice_image_repository"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dockerdeployment",
            old_name="tag",
            new_name="image_tag",
        ),
    ]
