# Generated by Django 5.0.2 on 2024-04-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0062_rename_tag_dockerdeployment_image_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockerdeployment",
            name="image_tag",
            field=models.CharField(default="latest", max_length=255),
        ),
    ]
