# Generated by Django 5.0.2 on 2024-04-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0062_rename_tag_dockerdeployment_image_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockerdeployment",
            name="deployment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CANCELLED", "Cancelled"),
                    ("HEALTHY", "Healthy"),
                    ("UNHEALTHY", "UnHealthy"),
                    ("OFFLINE", "Offline"),
                    ("SLEEPING", "Sleeping"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="gitdeployment",
            name="deployment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CANCELLED", "Cancelled"),
                    ("HEALTHY", "Healthy"),
                    ("UNHEALTHY", "UnHealthy"),
                    ("OFFLINE", "Offline"),
                    ("SLEEPING", "Sleeping"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
