# Generated by Django 5.0.2 on 2024-04-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0063_alter_dockerdeployment_deployment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockerdeployment",
            name="deployment_status_reason",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="gitdeployment",
            name="deployment_status_reason",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dockerdeployment",
            name="deployment_status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("PENDING", "Pending"),
                    ("CANCELLED", "Cancelled"),
                    ("HEALTHY", "Healthy"),
                    ("UNHEALTHY", "UnHealthy"),
                    ("OFFLINE", "Offline"),
                    ("SLEEPING", "Sleeping"),
                ],
                default="QUEUED",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="gitdeployment",
            name="deployment_status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("PENDING", "Pending"),
                    ("CANCELLED", "Cancelled"),
                    ("HEALTHY", "Healthy"),
                    ("UNHEALTHY", "UnHealthy"),
                    ("OFFLINE", "Offline"),
                    ("SLEEPING", "Sleeping"),
                ],
                default="QUEUED",
                max_length=10,
            ),
        ),
    ]
