# Generated by Django 5.0.2 on 2024-04-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0067_alter_dockerdeployment_deployment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockerdeployment",
            name="deployment_status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("PREPARING", "Preparing"),
                    ("STARTING", "Starting"),
                    ("RESTARTING", "Restarting"),
                    ("HEALTHY", "Healthy"),
                    ("UNHEALTHY", "Unhealthy"),
                    ("OFFLINE", "Offline"),
                ],
                default="QUEUED",
                max_length=10,
            ),
        ),
    ]
