# Generated by Django 5.0.2 on 2024-04-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0064_archiveddockerservice_image_tag_and_more"),
        ("zane_api", "0068_alter_dockerdeployment_deployment_status"),
    ]

    operations = []
