# Generated by Django 5.0.2 on 2024-04-26 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("zane_api", "0069_merge_20240426_1322"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockerdeployment",
            name="monitor_task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="django_celery_beat.periodictask",
            ),
        ),
    ]
