# Generated by Django 5.0.2 on 2024-04-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("zane_api", "0070_dockerdeployment_monitor_task"),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name="dockerdeployment",
        #     name="monitor_task",
        #     field=models.ForeignKey(
        #         null=True,
        #         on_delete=django.db.models.deletion.SET_NULL,
        #         to="django_celery_beat.periodictask",
        #     ),
        # ),
    ]
