# Generated by Django 5.0.2 on 2024-04-29 13:55

import django.db.models.deletion
import zane_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0071_alter_dockerdeployment_monitor_task"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[zane_api.validators.validate_url_path],
                    ),
                ),
                ("cmd", models.CharField(blank=True, max_length=255, null=True)),
                ("interval_seconds", models.PositiveIntegerField(default=15)),
                ("timeout_seconds", models.PositiveIntegerField(default=300)),
            ],
        ),
        migrations.AlterField(
            model_name="gitdeployment",
            name="deployment_status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("STARTING", "Starting"),
                    ("RESTARTING", "Restarting"),
                    ("BUILDING", "Building"),
                    ("CANCELLED", "Cancelled"),
                    ("HEALTHY", "Healthy"),
                    ("UNHEALTHY", "UnHealthy"),
                    ("OFFLINE", "Offline"),
                    ("SLEEPING", "Sleeping"),
                ],
                default="QUEUED",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dockerregistryservice",
            name="healthcheck",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zane_api.healthcheck",
            ),
        ),
        migrations.AddField(
            model_name="gitrepositoryservice",
            name="healthcheck",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zane_api.healthcheck",
            ),
        ),
    ]
