# Generated by Django 5.0.2 on 2024-04-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0072_healthcheck_alter_gitdeployment_deployment_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthcheck",
            name="cmd",
        ),
        migrations.RemoveField(
            model_name="healthcheck",
            name="path",
        ),
        migrations.AddField(
            model_name="healthcheck",
            name="type",
            field=models.CharField(
                choices=[("COMMAND", "Command"), ("PATH", "Path")],
                default="PATH",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="healthcheck",
            name="value",
            field=models.CharField(default="/", max_length=255),
        ),
    ]
