# Generated by Django 5.0.2 on 2024-05-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0074_alter_dockerdeployment_deployment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockerdeployment",
            name="deployment_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="gitdeployment",
            name="deployment_url",
            field=models.URLField(null=True),
        ),
    ]
