# Generated by Django 5.0.2 on 2024-05-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0076_rename_deployment_url_dockerdeployment_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
