# Generated by Django 5.0.2 on 2024-05-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0078_alter_url_is_primary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="url",
            name="is_primary",
        ),
    ]
