# Generated by Django 5.0.4 on 2024-05-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0079_remove_url_is_primary"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeploymentURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name="archiveddockerservice",
            name="deployment_urls",
            field=models.ManyToManyField(to="zane_api.deploymenturl"),
        ),
    ]
