# Generated by Django 5.0.4 on 2024-05-02 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0080_deploymenturl_archiveddockerservice_deployment_urls"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deploymenturl",
            old_name="url",
            new_name="domain",
        ),
    ]
