# Generated by Django 5.0.4 on 2024-05-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0083_alter_gitdeployment_deployment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcheck",
            name="timeout_seconds",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
