# Generated by Django 5.0.4 on 2024-05-06 17:27

import zane_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0084_alter_healthcheck_timeout_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="volume",
            name="hostPath",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[zane_api.validators.validate_url_path],
            ),
        ),
        migrations.AlterField(
            model_name="volume",
            name="containerPath",
            field=models.CharField(
                max_length=255, validators=[zane_api.validators.validate_url_path]
            ),
        ),
    ]
