# Generated by Django 5.0.4 on 2024-05-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0085_volume_hostpath_alter_volume_containerpath"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volume",
            name="containerPath",
            field=models.CharField(max_length=255),
        ),
    ]
