# Generated by Django 5.0.4 on 2024-05-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0086_alter_volume_containerpath"),
    ]

    operations = [
        migrations.RenameField(
            model_name="volume",
            old_name="containerPath",
            new_name="container_path",
        ),
        migrations.RenameField(
            model_name="volume",
            old_name="hostPath",
            new_name="host_path",
        ),
    ]
