# Generated by Django 5.0.4 on 2024-05-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0090_volume_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedvolume",
            name="mode",
            field=models.CharField(
                choices=[("READ_ONLY", "Read-Only"), ("READ_WRITE", "Read-Write")],
                default="READ_WRITE",
                max_length=255,
            ),
        ),
    ]
