# Generated by Django 5.0.4 on 2024-05-07 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("zane_api", "0091_archivedvolume_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cron",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="django_celery_beat.crontabschedule",
            ),
        ),
    ]
