# Generated by Django 5.0.4 on 2024-05-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0092_alter_cron_schedule"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gitworkerdeployment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="gitworkerdeployment",
            name="logs",
        ),
        migrations.RemoveField(
            model_name="gitworkerdeployment",
            name="worker",
        ),
        migrations.DeleteModel(
            name="DockerWorkerDeployment",
        ),
        migrations.DeleteModel(
            name="GitWorkerDeployment",
        ),
    ]
