# Generated by Django 5.0.4 on 2024-05-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0093_alter_gitworkerdeployment_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gitrepositoryworker",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="gitrepositoryworker",
            name="project",
        ),
        migrations.DeleteModel(
            name="DockerRegistryWorker",
        ),
        migrations.DeleteModel(
            name="GitRepositoryWorker",
        ),
    ]
