# Generated by Django 5.0.4 on 2024-05-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0096_dockerregistryservice_network_alias_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dockerdeployment",
            old_name="deployment_status_reason",
            new_name="status_reason",
        ),
    ]
