# Generated by Django 5.0.4 on 2024-05-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zane_api",
            "0097_rename_deployment_status_reason_dockerdeployment_status_reason",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockerdeployment",
            name="network_alias",
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="dockerregistryservice",
            name="network_alias",
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="gitdeployment",
            name="network_alias",
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="gitrepositoryservice",
            name="network_alias",
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
