# Generated by Django 5.0.4 on 2024-05-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0098_alter_dockerdeployment_network_alias_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dockerdeployment",
            name="network_alias",
        ),
        migrations.RemoveField(
            model_name="gitdeployment",
            name="network_alias",
        ),
    ]
