# Generated by Django 5.0.4 on 2024-05-13 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0099_remove_dockerdeployment_network_alias_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archivedproject",
            options={"ordering": ["-archived_at"]},
        ),
    ]
