# Generated by Django 5.0.4 on 2024-05-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0100_alter_archivedproject_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
