# Generated by Django 5.0.4 on 2024-05-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0102_rename_deployment_status_gitdeployment_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedproject",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
