# Generated by Django 5.0.4 on 2024-05-21 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0103_archivedproject_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockerdeployment",
            name="service_snapshot",
            field=models.JSONField(),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="DockerDeploymentChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("UPDATE", "update"),
                            ("DELETE", "delete"),
                            ("ADD", "add"),
                        ],
                        max_length=10,
                    ),
                ),
                ("field", models.CharField(max_length=255)),
                ("item_id", models.CharField(max_length=255, null=True)),
                ("old_value", models.JSONField(null=True)),
                ("new_value", models.JSONField(null=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="zane_api.dockerdeployment",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changesets",
                        to="zane_api.dockerregistryservice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
