# Generated by Django 5.0.4 on 2024-05-21 03:53

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0104_dockerdeployment_service_snapshot_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockerdeploymentchange",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=11,
                max_length=255,
                prefix="chg_dkr_",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="dockerenvvariable",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=11,
                max_length=255,
                prefix="env_dkr_",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="healthcheck",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=11,
                max_length=255,
                prefix="htc_",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="portconfiguration",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=11,
                max_length=255,
                prefix="prt_",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="url",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=11,
                max_length=255,
                prefix="url_",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
