# Generated by Django 5.0.4 on 2024-05-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("zane_api", "0104_dockerdeployment_zane_api_do_status_00a3ce_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dockerdeployment",
            index=models.Index(
                fields=["is_current_production"], name="zane_api_do_is_curr_567feb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gitdeployment",
            index=models.Index(
                fields=["is_current_production"], name="zane_api_gi_is_curr_d96726_idx"
            ),
        ),
    ]
