# Generated by Django 5.0.4 on 2024-05-21 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0105_alter_dockerdeploymentchange_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dockerregistryservice",
            old_name="image_repository",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="dockerdeployment",
            name="image_tag",
        ),
    ]
