# Generated by Django 5.0.4 on 2024-05-23 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zane_api",
            "0106_rename_image_repository_dockerregistryservice_image_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="archiveddockerservice",
            old_name="image_repository",
            new_name="image",
        ),
        migrations.RemoveField(
            model_name="archiveddockerservice",
            name="image_tag",
        ),
        migrations.AddField(
            model_name="dockerdeploymentchange",
            name="applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="dockerdeploymentchange",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="changes",
                to="zane_api.dockerregistryservice",
            ),
        ),
    ]
