# Generated by Django 5.0.4 on 2024-05-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zane_api",
            "0107_rename_image_repository_archiveddockerservice_image_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dockerdeploymentchange",
            index=models.Index(fields=["field"], name="zane_api_do_field_92f446_idx"),
        ),
    ]
