# Generated by Django 5.0.4 on 2024-05-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0108_dockerdeploymentchange_zane_api_do_field_92f446_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockerregistryservice",
            name="image",
            field=models.CharField(max_length=510, null=True),
        ),
    ]
