# Generated by Django 5.0.4 on 2024-05-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0109_alter_dockerregistryservice_image"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dockerdeploymentchange",
            index=models.Index(
                fields=["applied"], name="zane_api_do_applied_b4f806_idx"
            ),
        ),
    ]
