# Generated by Django 5.0.4 on 2024-05-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0110_dockerdeploymentchange_zane_api_do_applied_b4f806_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="volume",
            index=models.Index(
                fields=["container_path"], name="zane_api_vo_contain_4b16be_idx"
            ),
        ),
    ]
