# Generated by Django 5.0.4 on 2024-05-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0111_volume_zane_api_vo_contain_4b16be_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dockerdeploymentchange",
            index=models.Index(fields=["type"], name="zane_api_do_type_bdf22b_idx"),
        ),
    ]
