# Generated by Django 5.0.4 on 2024-05-27 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0105_dockerdeployment_zane_api_do_is_curr_567feb_idx_and_more"),
        ("zane_api", "0112_dockerdeploymentchange_zane_api_do_type_bdf22b_idx"),
    ]

    operations = []
