# Generated by Django 5.0.4 on 2024-05-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0113_merge_20240527_1741"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockerdeployment",
            name="service_snapshot",
            field=models.JSONField(null=True),
        ),
    ]
