# Generated by Django 5.0.4 on 2024-05-28 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0114_alter_dockerdeployment_service_snapshot"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dockerenvvariable",
            unique_together={("key", "service")},
        ),
    ]
