# Generated by Django 5.0.4 on 2024-05-30 10:28

import zane_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0116_portconfiguration_zane_api_po_host_ef8ffd_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volume",
            name="host_path",
            field=models.CharField(
                max_length=255,
                null=True,
                unique=True,
                validators=[zane_api.validators.validate_url_path],
            ),
        ),
    ]
