# Generated by Django 5.0.4 on 2024-06-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0119_alter_dockerdeploymentchange_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockerdeployment",
            name="is_current_production",
            field=models.BooleanField(default=False),
        ),
    ]
