# Generated by Django 5.0.4 on 2024-06-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0120_alter_dockerdeployment_is_current_production"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dockerregistryservice",
            name="docker_credentials_password",
        ),
        migrations.RemoveField(
            model_name="dockerregistryservice",
            name="docker_credentials_username",
        ),
        migrations.AddField(
            model_name="dockerregistryservice",
            name="credentials",
            field=models.JSONField(max_length=255, null=True),
        ),
    ]
