# Generated by Django 5.0.4 on 2024-06-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zane_api",
            "0121_remove_dockerregistryservice_docker_credentials_password_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archiveddockerservice",
            name="docker_credentials_password",
        ),
        migrations.RemoveField(
            model_name="archiveddockerservice",
            name="docker_credentials_username",
        ),
        migrations.AddField(
            model_name="archiveddockerservice",
            name="credentials",
            field=models.JSONField(max_length=255, null=True),
        ),
    ]
