# Generated by Django 5.0.4 on 2024-06-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zane_api",
            "0122_remove_archiveddockerservice_docker_credentials_password_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockerdeployment",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("CANCELLED", "Cancelled"),
                    ("FAILED", "Failed"),
                    ("PREPARING", "Preparing"),
                    ("STARTING", "Starting"),
                    ("RESTARTING", "Restarting"),
                    ("HEALTHY", "Healthy"),
                    ("UNHEALTHY", "Unhealthy"),
                    ("REMOVED", "Removed"),
                ],
                default="QUEUED",
                max_length=10,
            ),
        ),
    ]
