# Generated by Django 5.0.4 on 2024-06-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0123_alter_dockerdeployment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archiveddockerservice",
            name="deployment_urls",
        ),
        migrations.DeleteModel(
            name="DeploymentURL",
        ),
        migrations.AddField(
            model_name="archiveddockerservice",
            name="deployment_urls",
            field=models.JSONField(default=[]),
        ),
    ]
