# Generated by Django 5.0.4 on 2024-06-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0124_remove_archiveddockerservice_deployment_urls_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveddockerservice",
            name="deployment_hashes",
            field=models.JSONField(default=[]),
        ),
    ]
