# Generated by Django 5.0.4 on 2024-06-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0125_archiveddockerservice_deployment_hashes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archiveddockerservice",
            name="deployment_hashes",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="archiveddockerservice",
            name="deployment_urls",
            field=models.JSONField(default=list),
        ),
    ]
