# Generated by Django 5.0.4 on 2024-06-05 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0126_alter_archiveddockerservice_deployment_hashes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dockerdeployment",
            options={"ordering": ("-created_at",)},
        ),
    ]
