# Generated by Django 5.0.4 on 2024-06-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0128_dockerdeployment_zane_api_do_url_981d00_idx"),
    ]

    operations = [
        migrations.RenameField(
            model_name="httplog",
            old_name="request_domain",
            new_name="request_host",
        ),
        migrations.RenameField(
            model_name="httplog",
            old_name="ip",
            new_name="request_ip",
        ),
        migrations.RenameField(
            model_name="httplog",
            old_name="path",
            new_name="request_uri",
        ),
        migrations.RenameField(
            model_name="simplelog",
            old_name="log_type",
            new_name="level",
        ),
        migrations.AddField(
            model_name="httplog",
            name="service_id",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="simplelog",
            name="service_id",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="simplelog",
            name="source",
            field=models.CharField(
                choices=[
                    ("SYSTEM", "System Logs"),
                    ("PROXY", "Proxy Logs"),
                    ("SERVICE", "Service Logs"),
                ],
                default="SERVICE",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(
                fields=["service_id"], name="zane_api_ht_service_7e2352_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(fields=["status"], name="zane_api_ht_status_28ab6e_idx"),
        ),
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(
                fields=["request_host"], name="zane_api_ht_request_3f1f93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(
                fields=["request_uri"], name="zane_api_ht_request_56a459_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="simplelog",
            index=models.Index(fields=["source"], name="zane_api_si_source_bba065_idx"),
        ),
        migrations.AddIndex(
            model_name="simplelog",
            index=models.Index(
                fields=["service_id"], name="zane_api_si_service_d393fd_idx"
            ),
        ),
    ]
