# Generated by Django 5.0.4 on 2024-06-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0129_rename_request_domain_httplog_request_host_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simplelog",
            name="content",
            field=models.JSONField(null=True),
        ),
    ]
