# Generated by Django 5.0.4 on 2024-06-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0131_simplelog_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="simplelog",
            name="deployment_id",
            field=models.CharField(null=True),
        ),
        migrations.AddIndex(
            model_name="simplelog",
            index=models.Index(
                fields=["deployment_id"], name="zane_api_si_deploym_ae4569_idx"
            ),
        ),
    ]
