# Generated by Django 5.0.4 on 2024-06-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0132_simplelog_deployment_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dockerdeployment",
            name="logs",
        ),
        migrations.AddField(
            model_name="httplog",
            name="deployment_id",
            field=models.CharField(null=True),
        ),
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(
                fields=["deployment_id"], name="zane_api_ht_deploym_d671e6_idx"
            ),
        ),
    ]
