# Generated by Django 5.0.4 on 2024-06-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zane_api",
            "0133_remove_dockerdeployment_logs_httplog_deployment_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dockerdeployment",
            name="http_logs",
        ),
        migrations.RemoveField(
            model_name="gitdeployment",
            name="http_logs",
        ),
        migrations.RemoveField(
            model_name="gitdeployment",
            name="logs",
        ),
        migrations.AddField(
            model_name="httplog",
            name="time",
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(fields=["time"], name="zane_api_ht_time_b680fd_idx"),
        ),
        migrations.AddIndex(
            model_name="simplelog",
            index=models.Index(fields=["level"], name="zane_api_si_level_c2fb11_idx"),
        ),
        migrations.AddIndex(
            model_name="simplelog",
            index=models.Index(fields=["time"], name="zane_api_si_time_f4e15d_idx"),
        ),
    ]
