# Generated by Django 5.0.4 on 2024-06-30 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0134_remove_dockerdeployment_http_logs_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="httplog",
            options={"ordering": ("time",)},
        ),
        migrations.AlterModelOptions(
            name="simplelog",
            options={"ordering": ("time",)},
        ),
    ]
