# Generated by Django 5.0.4 on 2024-07-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0138_alter_dockerdeployment_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="httplog",
            old_name="request_duration_ms",
            new_name="request_duration_ns",
        ),
    ]
