# Generated by Django 5.0.4 on 2024-07-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0140_httplog_request_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httplog",
            name="request_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
