# Generated by Django 5.0.4 on 2024-07-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0142_httplog_zane_api_ht_request_5fa6b3_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="httplog",
            name="zane_api_ht_request_56a459_idx",
        ),
        migrations.RenameField(
            model_name="httplog",
            old_name="request_uri",
            new_name="request_path",
        ),
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(
                fields=["request_path"], name="zane_api_ht_request_d290e0_idx"
            ),
        ),
    ]
