# Generated by Django 5.0.4 on 2024-07-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0143_remove_httplog_zane_api_ht_request_56a459_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="httplog",
            name="request_query",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
