# Generated by Django 5.0.4 on 2024-07-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0144_httplog_request_query"),
    ]

    operations = [
        migrations.AddField(
            model_name="httplog",
            name="request_protocol",
            field=models.CharField(
                choices=[
                    ("HTTP/1.0", "HTTP/1.0"),
                    ("HTTP/1.1", "HTTP/1.1"),
                    ("HTTP/2.0", "HTTP/2.0"),
                    ("HTTP/3.0", "HTTP/3.0"),
                ],
                default="HTTP/1.1",
                max_length=10,
            ),
        ),
    ]
