# Generated by Django 5.0.4 on 2024-07-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0145_httplog_request_protocol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httplog",
            name="request_duration_ns",
            field=models.BigIntegerField(),
        ),
    ]
