# Generated by Django 5.0.4 on 2024-08-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0146_alter_httplog_request_duration_ns"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockerdeployment",
            name="commit_message",
            field=models.TextField(default="update service"),
        ),
        migrations.AddField(
            model_name="dockerdeployment",
            name="deploy_duration_in_ms",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
