# Generated by Django 5.0.4 on 2024-08-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0147_dockerdeployment_commit_message_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dockerdeployment",
            options={"ordering": ("-queued_at",)},
        ),
        migrations.RenameField(
            model_name="dockerdeployment",
            old_name="created_at",
            new_name="queued_at",
        ),
        migrations.RenameField(
            model_name="gitdeployment",
            old_name="created_at",
            new_name="queued_at",
        ),
        migrations.RemoveField(
            model_name="dockerdeployment",
            name="deploy_duration_in_ms",
        ),
        migrations.AddField(
            model_name="dockerdeployment",
            name="finished_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="gitdeployment",
            name="finished_at",
            field=models.DateTimeField(null=True),
        ),
    ]
