# Generated by Django 5.0.4 on 2024-08-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0148_alter_dockerdeployment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockerdeployment",
            name="started_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="gitdeployment",
            name="started_at",
            field=models.DateTimeField(null=True),
        ),
    ]
