# Generated by Django 5.0.4 on 2024-08-16 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0149_dockerdeployment_started_at_gitdeployment_started_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dockerdeployment",
            name="monitor_task",
        ),
    ]
