# Generated by Django 5.0.4 on 2024-08-19 01:26

import zane_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0150_remove_dockerdeployment_monitor_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volume",
            name="host_path",
            field=models.CharField(
                max_length=255,
                null=True,
                validators=[zane_api.validators.validate_url_path],
            ),
        ),
    ]
