# Generated by Django 5.0.4 on 2024-08-19 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0151_alter_volume_host_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicecommandcron",
            name="cron_ptr",
        ),
        migrations.RemoveField(
            model_name="httpcron",
            name="cron_ptr",
        ),
        migrations.RemoveField(
            model_name="servicecommandcron",
            name="dockerService",
        ),
        migrations.RemoveField(
            model_name="servicecommandcron",
            name="gitService",
        ),
        migrations.DeleteModel(
            name="CRON",
        ),
        migrations.DeleteModel(
            name="HttpCRON",
        ),
        migrations.DeleteModel(
            name="ServiceCommandCRON",
        ),
    ]
