# Generated by Django 5.0.4 on 2024-09-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0154_archiveddockerservice_deployments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archiveddockerservice",
            name="deployment_hashes",
        ),
        migrations.RemoveField(
            model_name="archiveddockerservice",
            name="deployment_urls",
        ),
        migrations.AddField(
            model_name="archivedurl",
            name="original_id",
            field=models.CharField(null=True),
        ),
    ]
