# Generated by Django 5.0.4 on 2024-09-19 17:01

import zane_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0155_remove_archiveddockerservice_deployment_hashes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="domain",
            field=models.CharField(
                max_length=1000,
                validators=[zane_api.validators.validate_url_domain],
            ),
            preserve_default=False,
        ),
    ]
