# Generated by Django 5.0.4 on 2024-09-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0158_url_redirect_permanent_url_redirect_to"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="url",
            name="redirect_permanent",
        ),
        migrations.AlterField(
            model_name="url",
            name="redirect_to",
            field=models.JSONField(max_length=2000, null=True),
        ),
    ]
