# Generated by Django 5.0.4 on 2024-11-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0159_remove_url_redirect_permanent_alter_url_redirect_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="simplelog",
            name="content_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
