# Generated by Django 5.0.4 on 2024-11-13 20:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0161_auto_20241112_2228"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httplog",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="simplelog",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
