# Generated by Django 5.1.3 on 2024-12-19 01:37

from django.db import migrations

from ..temporal.main import delete_schedule
import asyncio
from django.conf import settings


def delete_logs_cleanup_schedule(apps, schema_editor):
    if not settings.TESTING:
        asyncio.run(delete_schedule("daily-logs-cleanup", prefix=""))


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0165_auto_20241117_2321"),
    ]

    operations = [
        migrations.RunPython(
            delete_logs_cleanup_schedule,
            reverse_code=migrations.RunPython.noop,  # No reverse operation needed for deletion
        ),
    ]
