# Generated by Django 5.0.4 on 2024-11-29 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0165_auto_20241117_2321"),
    ]

    operations = []
