# Generated by Django 5.1.3 on 2024-12-29 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0165_auto_20241117_2321"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SimpleLog",
        ),
    ]
