# Generated by Django 5.1.3 on 2025-01-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0166_delete_simplelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="dockerregistryservice",
            name="deploy_token",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="gitrepositoryservice",
            name="deploy_token",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="dockerdeploymentchange",
            name="field",
            field=models.CharField(
                choices=[
                    ("source", "source"),
                    ("command", "command"),
                    ("healthcheck", "healthcheck"),
                    ("volumes", "volumes"),
                    ("env_variables", "env variables"),
                    ("urls", "urls"),
                    ("ports", "ports"),
                    ("resource_limits", "resource limits"),
                ],
                max_length=255,
            ),
        ),
    ]
