# Generated by Django 5.1.3 on 2025-01-07 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0167_dockerregistryservice_deploy_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockerregistryservice",
            name="deploy_token",
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="gitrepositoryservice",
            name="deploy_token",
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
