# Generated by Django 5.1.3 on 2025-01-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0168_alter_dockerregistryservice_deploy_token_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(
                fields=["request_duration_ns"], name="zane_api_ht_request_45fca4_idx"
            ),
        ),
    ]
