# Generated by Django 5.1.3 on 2025-01-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0169_httplog_zane_api_ht_request_45fca4_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="httplog",
            name="request_user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(
                fields=["request_user_agent"], name="zane_api_ht_request_db6570_idx"
            ),
        ),
    ]
