# Generated by Django 5.1.3 on 2025-01-18 01:52

from django.db import migrations
from django.db.models import F, Func, Value


def populate_user_agent(apps, schema_editor):
    HttpLog = apps.get_model("zane_api", "HttpLog")

    HttpLog.objects.filter(request_headers__icontains="User-Agent").update(
        request_user_agent=Func(
            F("request_headers"),
            Value("User-Agent"),
            Value("0"),
            function="jsonb_extract_path_text",  # Adjust function for PostgreSQL
        )
    )


def rollback_user_agent(apps, schema_editor):
    HttpLog = apps.get_model("zane_api", "HttpLog")

    # Clear the user_agent field
    HttpLog.objects.update(request_user_agent=None)


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0170_httplog_request_user_agent_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_user_agent,
            reverse_code=rollback_user_agent,
        ),
    ]
