# Generated by Django 5.1.3 on 2025-01-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0172_auto_20250118_0233"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(
                fields=["request_ip"], name="zane_api_ht_request_294e3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(
                fields=["request_id"], name="zane_api_ht_request_a15dee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(
                fields=["request_query"], name="zane_api_ht_request_6430c9_idx"
            ),
        ),
    ]
