# Generated by Django 5.1.3 on 2025-01-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0173_httplog_zane_api_ht_request_294e3f_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="httplog",
            options={"ordering": ("-time",)},
        ),
        migrations.RemoveIndex(
            model_name="httplog",
            name="zane_api_ht_request_45fca4_idx",
        ),
    ]
