# Generated by Django 5.1.3 on 2025-02-07 01:31

import django.core.validators
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0174_alter_httplog_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockerdeploymentchange",
            name="field",
            field=models.CharField(
                choices=[
                    ("source", "source"),
                    ("command", "command"),
                    ("healthcheck", "healthcheck"),
                    ("volumes", "volumes"),
                    ("env_variables", "env variables"),
                    ("urls", "urls"),
                    ("ports", "ports"),
                    ("resource_limits", "resource limits"),
                    ("config", "config"),
                ],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=11,
                        max_length=255,
                        prefix="cf_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=1)
                        ],
                    ),
                ),
                ("mount_path", models.CharField(max_length=255)),
                ("contents", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["mount_path"], name="zane_api_co_mount_p_a2cd24_idx"
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="dockerregistryservice",
            name="configs",
            field=models.ManyToManyField(to="zane_api.config"),
        ),
        migrations.AddField(
            model_name="gitrepositoryservice",
            name="configs",
            field=models.ManyToManyField(to="zane_api.config"),
        ),
    ]
