# Generated by Django 5.1.3 on 2025-02-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0176_alter_dockerdeploymentchange_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="language",
            field=models.CharField(default="plaintext", max_length=255),
        ),
    ]
