# Generated by Django 5.1.3 on 2025-02-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0179_config_version"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="config",
            index=models.Index(
                fields=["version"], name="zane_api_co_version_e16370_idx"
            ),
        ),
    ]
