# Generated by Django 5.1.3 on 2025-02-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0180_config_zane_api_co_version_e16370_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="associated_port",
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name="url",
            name="primary",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(
                fields=["primary"], name="zane_api_ur_primary_b76657_idx"
            ),
        ),
    ]
