# Generated by Django 5.1.3 on 2025-02-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0181_url_associated_port_url_primary_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="url",
            name="zane_api_ur_primary_b76657_idx",
        ),
        migrations.RemoveField(
            model_name="url",
            name="primary",
        ),
        migrations.AddField(
            model_name="healthcheck",
            name="associated_port",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="url",
            name="associated_port",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
