# Generated by Django 5.1.3 on 2025-02-08 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0182_remove_url_zane_api_ur_primary_b76657_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeploymentURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.URLField(null=True)),
                (
                    "deployment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="zane_api.dockerdeployment",
                    ),
                ),
            ],
        ),
    ]
