# Generated by Django 5.1.3 on 2025-02-08 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0183_deploymenturl"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dockerdeployment",
            name="zane_api_do_url_981d00_idx",
        ),
        migrations.RemoveField(
            model_name="dockerdeployment",
            name="url",
        ),
        migrations.RemoveField(
            model_name="gitdeployment",
            name="url",
        ),
    ]
