# Generated by Django 5.1.3 on 2025-02-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0185_deploymenturl_zane_api_de_domain_7cec98_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="deploymenturl",
            name="port",
            field=models.PositiveIntegerField(default=80),
        ),
    ]
