# Generated by Django 5.1.3 on 2025-02-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0186_deploymenturl_port"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portconfiguration",
            name="host",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
