# Generated by Django 5.1.3 on 2025-02-09 03:36

from django.db import migrations
from django.db.models import Q


def replace_associated_ports_in_urls(apps, schema_editor):
    DockerRegistryService = apps.get_model("zane_api", "DockerRegistryService")

    for service in DockerRegistryService.objects.all():
        http_port = service.ports.filter(host__in=[80, 443, 0]).first()

        if http_port is not None:
            service.urls.filter(redirect_to__isnull=True).update(
                associated_port=http_port.forwarded
            )
            http_port.delete()


def rollback_associated_ports_in_urls(apps, schema_editor):
    DockerRegistryService = apps.get_model("zane_api", "DockerRegistryService")

    for service in DockerRegistryService.objects.all():
        service.urls.update(associated_port=None)


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0188_archivedurl_associated_port"),
    ]

    operations = [
        migrations.RunPython(
            replace_associated_ports_in_urls,
            reverse_code=rollback_associated_ports_in_urls,  # This clears content_text when rolling back
        ),
    ]
