# Generated by Django 5.1.3 on 2025-02-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0189_auto_20250209_0336"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deploymenturl",
            name="domain",
            field=models.URLField(),
        ),
    ]
