# Generated by Django 5.1.3 on 2025-02-09 22:04

from django.db import migrations


def replace_associated_ports_in_healthchecks(apps, schema_editor):
    DockerRegistryService = apps.get_model("zane_api", "DockerRegistryService")

    for service in DockerRegistryService.objects.filter(
        healthcheck__isnull=False, healthcheck__type="PATH"
    ).select_related("healthcheck"):
        http_port = service.ports.filter(host__in=[80, 443, 0]).first()

        if http_port is not None:
            service.healthcheck.associated_port = http_port.forwarded
            http_port.delete()
        else:
            url_with_http_port = service.urls.filter(
                associated_port__isnull=False
            ).first()
            if url_with_http_port is not None:
                service.healthcheck.associated_port = url_with_http_port.associated_port
        service.healthcheck.save()


def rollback_associated_ports_in_healthchecks(apps, schema_editor):
    DockerRegistryService = apps.get_model("zane_api", "DockerRegistryService")

    for service in DockerRegistryService.objects.filter(
        healthcheck__isnull=False, healthcheck__type="PATH"
    ).select_related("healthcheck"):
        service.healthcheck.associated_port = None
        service.healthcheck.save()


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0190_alter_deploymenturl_domain"),
    ]

    operations = [
        migrations.RunPython(
            replace_associated_ports_in_healthchecks,
            reverse_code=rollback_associated_ports_in_healthchecks,  # This clears content_text when rolling back
        ),
    ]
