# Generated by Django 5.1.3 on 2025-02-10 22:23

from django.db import migrations


def remove_associated_ports_in_urls_with_redirect(apps, schema_editor):
    URL = apps.get_model("zane_api", "URL")

    URL.objects.filter(redirect_to__isnull=False).update(associated_port=None)


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0191_auto_20250209_2204"),
    ]

    operations = [
        migrations.RunPython(
            remove_associated_ports_in_urls_with_redirect,
            reverse_code=migrations.RunPython.noop,
        )  # No reverse oper)
    ]
