# Generated by Django 5.1.3 on 2025-02-17 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0194_alter_dockerenvvariable_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cpu_percent', models.FloatField()),
                ('memory_bytes', models.PositiveBigIntegerField()),
                ('net_tx_bytes', models.PositiveBigIntegerField()),
                ('net_rx_bytes', models.PositiveBigIntegerField()),
                ('disk_read_bytes', models.PositiveBigIntegerField()),
                ('disk_writes_bytes', models.PositiveBigIntegerField()),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zane_api.dockerdeployment')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zane_api.dockerregistryservice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
