# Generated by Django 5.1.3 on 2025-02-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0195_servicemetric'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceMetric',
            new_name='ServiceMetrics',
        ),
        migrations.AddIndex(
            model_name='servicemetrics',
            index=models.Index(fields=['created_at'], name='zane_api_se_created_9e3b1b_idx'),
        ),
    ]
