# Generated by Django 5.1.3 on 2025-03-14 01:57

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0196_rename_servicemetric_servicemetrics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=15, max_length=255, prefix='project_env_', primary_key=True, serialize=False, unique=True)),
                ('name', models.SlugField(max_length=255)),
                ('immutable', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='zane_api.project')),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='zane_api_en_name_f76349_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('name', 'production')), fields=('project',), name='unique_production_per_project')],
                'unique_together': {('name', 'project')},
            },
        ),
    ]
