# Generated by Django 5.1.3 on 2025-03-14 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0196_rename_servicemetric_servicemetrics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.SlugField(max_length=255)),
                ('immutable', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zane_api.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('name', 'production')), fields=('project',), name='unique_production_per_project')],
                'unique_together': {('name', 'project')},
            },
        ),
    ]
