# Generated by Django 5.1.3 on 2025-03-14 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0200_archivedenvironment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerregistryservice',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zane_api.environment'),
        ),
    ]
