# Generated by Django 5.1.3 on 2025-03-14 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0202_auto_20250314_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerregistryservice',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zane_api.environment'),
        ),
    ]
