# Generated by Django 5.1.3 on 2025-03-14 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0203_alter_dockerregistryservice_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockerregistryservice',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='zane_api.environment'),
        ),
    ]
