# Generated by Django 5.1.3 on 2025-03-14 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0204_alter_dockerregistryservice_environment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environment',
            old_name='immutable',
            new_name='is_preview',
        ),
    ]
