# Generated by Django 5.1.3 on 2025-03-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0205_rename_immutable_environment_is_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedenvironment',
            name='immutable',
        ),
    ]
