# Generated by Django 5.1.3 on 2025-03-15 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0206_remove_archivedenvironment_immutable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gitrepositoryservice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dockerregistryservice',
            unique_together={('slug', 'project', 'environment')},
        ),
    ]
