# Generated by Django 5.1.3 on 2025-03-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0207_alter_gitrepositoryservice_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveddockerservice',
            name='environment_id',
            field=models.CharField(null=True),
        ),
    ]
