# Generated by Django 5.1.3 on 2025-03-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0209_alter_dockerregistryservice_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerdeployment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gitdeployment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
