# Generated by Django 5.1.3 on 2025-03-20 22:11

import django.db.models.deletion
import shortuuid.django_fields
import zane_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0210_dockerdeployment_updated_at_gitdeployment_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentEnvVariable',
            fields=[
                ('key', models.CharField(max_length=255, validators=[zane_api.validators.validate_env_name])),
                ('value', models.TextField(blank=True)),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=11, max_length=255, prefix='env_prj_', primary_key=True, serialize=False)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='zane_api.environment')),
            ],
            options={
                'unique_together': {('key', 'environment')},
            },
        ),
    ]
