# Generated by Django 5.1.3 on 2025-03-21 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0211_environmentenvvariable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnvironmentEnvVariable',
            new_name='SharedEnvVariable',
        ),
    ]
