# Generated by Django 5.1.3 on 2025-03-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0213_rename_dockerdeployment_deployment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DockerRegistryService',
            new_name='Service',
        ),
    ]
