# Generated by Django 5.1.3 on 2025-03-21 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0214_rename_dockerregistryservice_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DockerDeploymentChange',
            new_name='DeploymentChange',
        ),
        migrations.RenameModel(
            old_name='DockerEnvVariable',
            new_name='EnvVariable',
        ),
        migrations.RenameIndex(
            model_name='deploymentchange',
            new_name='zane_api_de_field_09af8d_idx',
            old_name='zane_api_do_field_92f446_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymentchange',
            new_name='zane_api_de_type_41ad82_idx',
            old_name='zane_api_do_type_bdf22b_idx',
        ),
        migrations.RenameIndex(
            model_name='deploymentchange',
            new_name='zane_api_de_applied_97ca9c_idx',
            old_name='zane_api_do_applied_b4f806_idx',
        ),
    ]
