# Generated by Django 5.1.3 on 2025-03-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zane_api', '0215_rename_dockerdeploymentchange_deploymentchange_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitdeployment',
            name='is_redeploy_of',
        ),
        migrations.RemoveField(
            model_name='gitdeployment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='gitrepositoryservice',
            name='configs',
        ),
        migrations.RemoveField(
            model_name='gitrepositoryservice',
            name='healthcheck',
        ),
        migrations.RemoveField(
            model_name='gitrepositoryservice',
            name='ports',
        ),
        migrations.RemoveField(
            model_name='gitrepositoryservice',
            name='project',
        ),
        migrations.RemoveField(
            model_name='gitrepositoryservice',
            name='urls',
        ),
        migrations.RemoveField(
            model_name='gitrepositoryservice',
            name='volumes',
        ),
        migrations.AddField(
            model_name='deployment',
            name='build_duration_in_ms',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='build_status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='QUEUED', max_length=10),
        ),
        migrations.AddField(
            model_name='deployment',
            name='commit_author_name',
            field=models.TextField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='commit_sha',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='pull_request_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='deployment',
            name='trigger_method',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('WEBHOOK', 'Webhook')], default='MANUAL', max_length=15),
        ),
        migrations.AddField(
            model_name='service',
            name='branch_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='commit_sha',
            field=models.CharField(default='HEAD', max_length=45),
        ),
        migrations.AddField(
            model_name='service',
            name='docker_build_context_dir',
            field=models.CharField(default='/', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='dockerfile_path',
            field=models.CharField(default='/Dockerfile', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='repository_url',
            field=models.URLField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('DOCKER_REGISTRY', 'Docker repository'), ('GIT_REPOSITORY', 'Git repository')], default='DOCKER_REGISTRY', max_length=15),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('CANCELLED', 'Cancelled'), ('CANCELLING', 'Cancelling'), ('FAILED', 'Failed'), ('PREPARING', 'Preparing'), ('BUILDING', 'Building'), ('STARTING', 'Starting'), ('RESTARTING', 'Restarting'), ('HEALTHY', 'Healthy'), ('UNHEALTHY', 'Unhealthy'), ('REMOVED', 'Removed'), ('SLEEPING', 'Sleeping')], default='QUEUED', max_length=10),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['build_status'], name='zane_api_de_build_s_a977bd_idx'),
        ),
        migrations.DeleteModel(
            name='GitDeployment',
        ),
        migrations.DeleteModel(
            name='GitRepositoryService',
        ),
    ]
