# Generated by Django 5.1.3 on 2025-03-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0216_remove_gitdeployment_is_redeploy_of_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="build_pack",
            field=models.CharField(
                choices=[("DOCKERFILE", "Dockerfile")],
                default="DOCKERFILE",
                max_length=20,
            ),
        ),
    ]
