# Generated by Django 5.1.3 on 2025-03-23 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0217_service_build_pack"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="build_pack",
            new_name="builder",
        ),
    ]
