# Generated by Django 5.1.3 on 2025-03-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0218_rename_build_pack_service_builder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="docker_build_context_dir",
        ),
        migrations.RemoveField(
            model_name="service",
            name="dockerfile_path",
        ),
        migrations.AddField(
            model_name="service",
            name="dockerfile_builder_options",
            field=models.JSONField(null=True),
        ),
    ]
