# Generated by Django 5.1.3 on 2025-03-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0220_alter_service_commit_sha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="builder",
            field=models.CharField(
                choices=[("DOCKERFILE", "Dockerfile")], max_length=20, null=True
            ),
        ),
    ]
