# Generated by Django 5.1.3 on 2025-03-23 05:02

from django.db import migrations

# Generated by Django 5.1.3 on 2025-03-23 04:44

from django.db import migrations


def set_commit_sha_and_builder_to_null(apps, schema_editor):
    Service = apps.get_model("zane_api", "Service")

    Service.objects.filter().update(commit_sha=None, builder=None)


def reset_commit_sha_and_builder(apps, schema_editor):
    Service = apps.get_model("zane_api", "Service")

    Service.objects.filter().update(commit_sha="HEAD", builder="DOCKERFILE")


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0221_alter_service_builder"),
    ]

    operations = [
        migrations.RunPython(
            set_commit_sha_and_builder_to_null,
            reverse_code=reset_commit_sha_and_builder,
        ),
    ]
