# Generated by Django 5.1.3 on 2025-03-25 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0223_remove_deployment_build_duration_in_ms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="zane_api.project",
            ),
        ),
    ]
