# Generated by Django 5.1.3 on 2025-03-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0224_alter_service_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deploymentchange",
            name="field",
            field=models.CharField(
                choices=[
                    ("source", "source"),
                    ("builder", "builder"),
                    ("command", "command"),
                    ("healthcheck", "healthcheck"),
                    ("volumes", "volumes"),
                    ("env_variables", "env variables"),
                    ("urls", "urls"),
                    ("ports", "ports"),
                    ("resource_limits", "resource limits"),
                    ("configs", "configs"),
                ],
                max_length=255,
            ),
        ),
    ]
