# Generated by Django 5.1.3 on 2025-03-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0226_alter_deploymentchange_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deployment",
            name="trigger_method",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("AUTO", "Automatic"),
                    ("WEBHOOK", "Webhook"),
                ],
                default="MANUAL",
                max_length=15,
            ),
        ),
    ]
