# Generated by Django 5.1.3 on 2025-03-26 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0227_alter_deployment_trigger_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedGitService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(max_length=255)),
                ("original_id", models.CharField(max_length=255)),
                ("resource_limits", models.JSONField(max_length=255, null=True)),
                ("healthcheck", models.JSONField(max_length=255, null=True)),
                ("environment_id", models.CharField(null=True)),
                ("repository_url", models.URLField(max_length=2048)),
                ("deployments", models.JSONField(default=list)),
                ("branch_name", models.CharField(max_length=255)),
                ("commit_sha", models.CharField(max_length=45)),
                ("builder", models.CharField(max_length=20)),
                ("dockerfile_builder_options", models.JSONField(null=True)),
                ("configs", models.ManyToManyField(to="zane_api.archivedconfig")),
                (
                    "ports",
                    models.ManyToManyField(to="zane_api.archivedportconfiguration"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="git_services",
                        to="zane_api.archivedproject",
                    ),
                ),
                ("urls", models.ManyToManyField(to="zane_api.archivedurl")),
                ("volumes", models.ManyToManyField(to="zane_api.archivedvolume")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
