# Generated by Django 5.1.3 on 2025-03-26 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0228_archivedgitservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedGitEnvVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archived_at", models.DateTimeField(auto_now_add=True)),
                ("key", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="env_variables",
                        to="zane_api.archivedgitservice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
