# Generated by Django 5.1.3 on 2025-04-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0230_archivedgitservice_command"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="static_dir_builder_options",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="builder",
            field=models.CharField(
                choices=[
                    ("DOCKERFILE", "Dockerfile"),
                    ("STATIC_DIR", "Static directory"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
