# Generated by Django 5.1.3 on 2025-04-09 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0232_service_nixpacks_builder_options_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="deployment",
            name="zane_api_de_build_s_a977bd_idx",
        ),
        migrations.RemoveField(
            model_name="deployment",
            name="build_status",
        ),
    ]
