# Generated by Django 5.1.3 on 2025-04-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0233_remove_deployment_zane_api_de_build_s_a977bd_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="railpack_builder_options",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="builder",
            field=models.CharField(
                choices=[
                    ("DOCKERFILE", "Dockerfile"),
                    ("STATIC_DIR", "Static directory"),
                    ("NIXPACKS", "Nixpacks"),
                    ("RAILPACK", "Railpack"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
