# Generated by Django 5.2 on 2025-05-18 22:38

from django.db import migrations


def noop(apps, schema_editor): ...


class Migration(migrations.Migration):
    dependencies = [
        ("zane_api", "0234_service_railpack_builder_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            noop,
        ),
    ]
