# Generated by Django 5.2 on 2025-07-01 03:24

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0235_auto_20250518_2238"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitApp",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=16,
                        max_length=255,
                        prefix="git_con_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GithubApp",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=14,
                        max_length=255,
                        prefix="gh_app_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("github_app_name", models.CharField(max_length=255, null=True)),
                ("app_id", models.CharField(max_length=255, null=True)),
                ("client_id", models.CharField(max_length=255, null=True)),
                ("installation_id", models.CharField(max_length=255, null=True)),
                ("client_secret", models.TextField(null=True)),
                ("webhook_secret", models.TextField(null=True)),
                ("private_key", models.TextField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GitlabApp",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=14,
                        max_length=255,
                        prefix="gl_app_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gitlab_url", models.URLField(default="https://gitlab.com")),
                ("app_id", models.CharField(max_length=255, null=True)),
                ("redirect_uri", models.URLField(max_length=255, null=True)),
                ("secret", models.TextField(null=True)),
                ("access_token", models.TextField(null=True)),
                ("refresh_token", models.TextField(null=True)),
                ("group_name", models.CharField(max_length=2000, null=True)),
                ("expires_at", models.PositiveBigIntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="service",
            name="git_app",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="zane_api.gitapp",
            ),
        ),
        migrations.AddField(
            model_name="gitapp",
            name="github",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zane_api.githubapp",
            ),
        ),
        migrations.AddField(
            model_name="gitapp",
            name="gitlab",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zane_api.gitlabapp",
            ),
        ),
    ]
