# Generated by Django 5.2 on 2025-07-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0236_gitapp_githubapp_gitlabapp_service_git_app_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="githubapp",
            name="name",
        ),
        migrations.AddField(
            model_name="githubapp",
            name="github_org_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="githubapp",
            name="slug",
            field=models.SlugField(max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gitlabapp",
            name="slug",
            field=models.SlugField(max_length=255),
            preserve_default=False,
        ),
    ]
