# Generated by Django 5.2 on 2025-07-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0237_remove_githubapp_name_githubapp_github_org_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="githubapp",
            name="slug",
        ),
    ]
