# Generated by Django 5.2 on 2025-07-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0238_remove_githubapp_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubapp",
            name="github_app_name",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
