# Generated by Django 5.2 on 2025-07-01 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0239_alter_githubapp_github_app_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="git_app",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="zane_api.gitapp",
            ),
        ),
    ]
