# Generated by Django 5.2 on 2025-07-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0240_alter_service_git_app"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="githubapp",
            name="github_app_name",
        ),
        migrations.AddField(
            model_name="githubapp",
            name="app_url",
            field=models.URLField(max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="githubapp",
            name="name",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
