# Generated by Django 5.2 on 2025-07-01 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zane_api",
            "0241_remove_githubapp_github_app_name_githubapp_app_url_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="githubapp",
            old_name="github_org_name",
            new_name="org_name",
        ),
        migrations.AlterField(
            model_name="gitapp",
            name="github",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zane_api.githubapp",
            ),
        ),
        migrations.AlterField(
            model_name="gitapp",
            name="gitlab",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zane_api.gitlabapp",
            ),
        ),
    ]
