# Generated by Django 5.2 on 2025-07-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0242_rename_github_org_name_githubapp_org_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubapp",
            name="app_id",
            field=models.CharField(max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="githubapp",
            name="app_url",
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name="githubapp",
            name="client_id",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="githubapp",
            name="client_secret",
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="githubapp",
            name="private_key",
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="githubapp",
            name="webhook_secret",
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
