# Generated by Django 5.2 on 2025-07-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0243_alter_githubapp_app_id_alter_githubapp_app_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubapp",
            name="app_id",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
