# Generated by Django 5.2 on 2025-07-02 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0244_alter_githubapp_app_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="githubapp",
            name="org_name",
        ),
    ]
