# Generated by Django 5.2 on 2025-07-03 13:50

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0245_remove_githubapp_org_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="GitRepository",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=14,
                        max_length=255,
                        prefix="repo_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner", models.SlugField(max_length=255)),
                ("repo", models.SlugField(max_length=255)),
                ("url", models.URLField(unique=True)),
                ("private", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="githubapp",
            name="repositories",
            field=models.ManyToManyField(to="zane_api.gitrepository"),
        ),
        migrations.AddField(
            model_name="gitlabapp",
            name="repositories",
            field=models.ManyToManyField(to="zane_api.gitrepository"),
        ),
    ]
