# Generated by Django 5.2 on 2025-07-03 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0001_initial"),
        ("zane_api", "0246_gitrepository_githubapp_repositories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gitapp",
            name="github",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="git_connectors.githubapp",
            ),
        ),
        migrations.RemoveField(
            model_name="gitlabapp",
            name="repositories",
        ),
        migrations.AlterField(
            model_name="gitapp",
            name="gitlab",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="git_connectors.gitlabapp",
            ),
        ),
        migrations.DeleteModel(
            name="GithubApp",
        ),
        migrations.DeleteModel(
            name="GitRepository",
        ),
        migrations.DeleteModel(
            name="GitlabApp",
        ),
    ]
