# Generated by Django 5.2 on 2025-07-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0016_gitlabapp_redirect_uri"),
        ("zane_api", "0247_alter_gitapp_github_remove_gitlabapp_repositories_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="gitapp",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("github__isnull", False),
                    ("gitlab__isnull", False),
                    _connector="OR",
                ),
                name="github_or_gitlab_not_null",
            ),
        ),
    ]
