# Generated by Django 5.2 on 2025-07-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0248_gitapp_github_or_gitlab_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="auto_deploy_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="service",
            name="cleanup_queue_on_deploy",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="service",
            name="watch_paths",
            field=models.CharField(default=None, max_length=2048, null=True),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["repository_url"], name="zane_api_se_reposit_30805d_idx"
            ),
        ),
    ]
