# Generated by Django 5.2 on 2025-07-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0249_service_auto_deploy_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deployment",
            name="trigger_method",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("AUTO", "Automatic"), ("API", "API")],
                default="MANUAL",
                max_length=15,
            ),
        ),
    ]
