# Generated by Django 5.2 on 2025-07-11 02:40

from django.db import migrations


def replace_trigger_method_with_api(apps, schema_editor):
    Deployment = apps.get_model("zane_api", "Deployment")

    Deployment.objects.filter(trigger_method="WEBHOOK").update(trigger_method="API")


def rollback_replace(apps, schema_editor):
    Deployment = apps.get_model("zane_api", "Deployment")

    Deployment.objects.filter(trigger_method="API").update(trigger_method="WEBHOOK")


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0250_alter_deployment_trigger_method"),
    ]

    operations = [
        migrations.RunPython(
            replace_trigger_method_with_api,
            reverse_code=rollback_replace,
        ),
    ]
