# Generated by Django 5.2 on 2025-07-14 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0251_auto_20250711_0240"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="cleanup_queue_on_deploy",
            new_name="cleanup_queue_on_auto_deploy",
        ),
    ]
