# Generated by Django 5.2 on 2025-07-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0253_alter_service_deploy_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="is_base_pr_env",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="service",
            name="pr_preview_env_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="service",
            name="pr_preview_limit",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="service",
            name="pr_preview_wildcard_domain",
            field=models.CharField(null=True),
        ),
    ]
