# Generated by Django 5.2 on 2025-07-31 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0254_environment_is_base_pr_env_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="pr_preview_env_enabled",
            new_name="preview_env_enabled",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="pr_preview_limit",
            new_name="preview_env_limit",
        ),
        migrations.RenameField(
            model_name="service",
            old_name="pr_preview_wildcard_domain",
            new_name="preview_wildcard_domain",
        ),
    ]
