# Generated by Django 5.2 on 2025-08-01 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zane_api",
            "0255_rename_pr_preview_env_enabled_service_preview_env_enabled_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="environment",
            name="is_base_pr_env",
        ),
        migrations.AddField(
            model_name="environment",
            name="preview_branch",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="environment",
            name="preview_commit_sha",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="environment",
            name="preview_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="environment",
            name="preview_external_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="environment",
            name="preview_pr_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="environment",
            name="preview_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preview_environments",
                to="zane_api.service",
            ),
        ),
        migrations.CreateModel(
            name="PreviewTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ttl_seconds", models.PositiveIntegerField(null=True)),
                ("auto_teardown", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "base_environment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zane_api.environment",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preview_templates",
                        to="zane_api.project",
                    ),
                ),
                (
                    "services_to_clone",
                    models.ManyToManyField(
                        blank=True,
                        related_name="preview_templates",
                        to="zane_api.service",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="environment",
            name="preview_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="zane_api.previewtemplate",
            ),
        ),
    ]
