# Generated by Django 5.2 on 2025-08-01 00:28

from django.db import migrations


def create_default_preview_template(apps, schema_editor):
    Project = apps.get_model("zane_api", "Project")

    for project in Project.objects.all():
        production_env = project.environments.get(name="production")
        template = project.preview_templates.create(
            base_environment=production_env,
            name="default-preview",
            is_default=True,
        )
        template.services_to_clone.add(*production_env.services.all())


def remove_preview_template(apps, schema_editor):
    Project = apps.get_model("zane_api", "Project")

    for project in Project.objects.all():
        project.preview_templates.filter(is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0256_remove_environment_is_base_pr_env_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_default_preview_template,
            reverse_code=remove_preview_template,
        )
    ]
