# Generated by Django 5.2 on 2025-08-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0257_auto_20250801_0028"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="preview_deploy_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name="previewtemplate",
            unique_together={("name", "project")},
        ),
    ]
