# Generated by Django 5.2 on 2025-08-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0258_environment_preview_deploy_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="previous_source_trigger",
            field=models.CharField(
                choices=[("API", "Api"), ("PULL_REQUEST", "Pull request")],
                max_length=30,
                null=True,
            ),
        ),
    ]
