# Generated by Django 5.2 on 2025-08-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0259_environment_previous_source_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="previewtemplate",
            name="clone_strategy",
            field=models.CharField(
                choices=[("ALL", "All services"), ("ONLY", "Only specific services")],
                default="ALL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="previewtemplate",
            name="services_to_clone",
            field=models.ManyToManyField(
                related_name="preview_templates", to="zane_api.service"
            ),
        ),
    ]
