# Generated by Django 5.2 on 2025-08-01 05:18

from django.db import migrations


def reset_default_preview_template_services(apps, schema_editor):
    Project = apps.get_model("zane_api", "Project")

    for project in Project.objects.all():
        template = project.preview_templates.filter(is_default=True).get()
        template.services_to_clone.clear()


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0260_previewtemplate_clone_strategy_and_more"),
    ]

    operations = [
        migrations.RunPython(
            reset_default_preview_template_services,
        )
    ]
