# Generated by Django 5.2 on 2025-08-01 06:40

import django.db.models.deletion
import shortuuid.django_fields
import zane_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0261_auto_20250801_0518"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedTemplateEnvVariable",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=255,
                        validators=[zane_api.validators.validate_env_name],
                    ),
                ),
                ("value", models.TextField(blank=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=11,
                        max_length=255,
                        prefix="env_tpl_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="zane_api.previewtemplate",
                    ),
                ),
            ],
            options={
                "unique_together": {("key", "template")},
            },
        ),
    ]
