# Generated by Django 5.2 on 2025-08-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0262_sharedtemplateenvvariable"),
    ]

    operations = [
        migrations.RenameField(
            model_name="environment",
            old_name="previous_source_trigger",
            new_name="preview_source_trigger",
        ),
    ]
