# Generated by Django 5.2 on 2025-08-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zane_api",
            "0263_rename_previous_source_trigger_environment_preview_source_trigger",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="previewtemplate",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="previewtemplate",
            constraint=models.UniqueConstraint(
                fields=("name", "project"), name="unique_template_name_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="previewtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("project",),
                name="unique_default_template_per_project",
            ),
        ),
    ]
