# Generated by Django 5.2 on 2025-08-01 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0264_alter_previewtemplate_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="preview_env_limit",
        ),
        migrations.RemoveField(
            model_name="service",
            name="preview_wildcard_domain",
        ),
        migrations.AddField(
            model_name="previewtemplate",
            name="preview_env_limit",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="previewtemplate",
            name="preview_wildcard_domain",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="previewtemplate",
            name="base_environment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="zane_api.environment",
            ),
            preserve_default=False,
        ),
    ]
