# Generated by Django 5.2 on 2025-08-01 07:42

import zane_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0265_remove_service_preview_env_limit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="previewtemplate",
            name="preview_wildcard_domain",
        ),
        migrations.AddField(
            model_name="previewtemplate",
            name="preview_root_domain",
            field=models.CharField(
                max_length=1000,
                null=True,
                validators=[zane_api.validators.validate_url_domain],
            ),
        ),
    ]
