# Generated by Django 5.2 on 2025-08-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0266_remove_previewtemplate_preview_wildcard_domain_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="preview_env_enabled",
            new_name="pr_preview_env_enabled",
        ),
    ]
