# Generated by Django 5.2 on 2025-08-01 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0267_rename_preview_env_enabled_service_pr_preview_env_enabled"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="pr_preview_env_enabled",
            new_name="pr_preview_envs_enabled",
        ),
    ]
