# Generated by Django 5.2 on 2025-08-02 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zane_api",
            "0268_rename_pr_preview_env_enabled_service_pr_preview_envs_enabled",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="previewtemplate",
            name="base_environment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zane_api.environment",
            ),
        ),
    ]
