# Generated by Django 5.2 on 2025-08-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0269_alter_previewtemplate_base_environment"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="preview_pr_title",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
