# Generated by Django 5.2 on 2025-08-03 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0270_environment_preview_pr_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="preview_git_app",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="zane_api.gitapp",
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="preview_repository_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="environment",
            name="preview_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preview_environments",
                to="zane_api.service",
            ),
        ),
    ]
