# Generated by Django 5.2 on 2025-08-03 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0271_environment_preview_git_app_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PreviewTemplate",
            new_name="PreviewEnvTemplate",
        ),
    ]
