# Generated by Django 5.2 on 2025-08-03 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0272_rename_previewtemplate_previewenvtemplate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="environment",
            name="preview_branch",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="preview_commit_sha",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="preview_deploy_approved",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="preview_expires_at",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="preview_external_url",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="preview_git_app",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="preview_pr_id",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="preview_pr_title",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="preview_repository_url",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="preview_service",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="preview_source_trigger",
        ),
        migrations.RemoveField(
            model_name="environment",
            name="preview_template",
        ),
        migrations.CreateModel(
            name="PreviewEnvMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_name", models.CharField(max_length=255)),
                ("commit_sha", models.CharField(default="HEAD", max_length=255)),
                ("pr_id", models.CharField(blank=True, max_length=255, null=True)),
                ("pr_title", models.CharField(blank=True, max_length=1000, null=True)),
                ("external_url", models.URLField()),
                ("repository_url", models.URLField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("deploy_approved", models.BooleanField(default=True)),
                (
                    "source_trigger",
                    models.CharField(
                        choices=[("API", "Api"), ("PULL_REQUEST", "Pull request")],
                        max_length=30,
                    ),
                ),
                (
                    "git_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zane_api.gitapp",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preview_environments",
                        to="zane_api.service",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="zane_api.previewenvtemplate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="environment",
            name="preview_metadata",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="zane_api.previewenvmetadata",
            ),
        ),
    ]
