# Generated by Django 5.2 on 2025-08-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0273_remove_environment_preview_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="previewenvmetadata",
            name="auto_teardown",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="previewenvmetadata",
            name="ttl_seconds",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
