# Generated by Django 5.2 on 2025-08-03 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0274_previewenvmetadata_auto_teardown_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="previewenvmetadata",
            name="expires_at",
        ),
        migrations.AlterField(
            model_name="environment",
            name="preview_metadata",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="environment",
                to="zane_api.previewenvmetadata",
            ),
        ),
    ]
