# Generated by Django 5.2 on 2025-08-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0275_remove_previewenvmetadata_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="previewenvtemplate",
            name="name",
            field=models.SlugField(max_length=100),
        ),
    ]
