# Generated by Django 5.2 on 2025-08-03 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0276_alter_previewenvtemplate_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="previewenvtemplate",
            old_name="name",
            new_name="slug",
        ),
    ]
