# Generated by Django 5.2 on 2025-08-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0277_rename_name_previewenvtemplate_slug"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="previewenvtemplate",
            name="unique_template_name_per_project",
        ),
        migrations.AddConstraint(
            model_name="previewenvtemplate",
            constraint=models.UniqueConstraint(
                fields=("slug", "project"), name="unique_template_name_per_project"
            ),
        ),
    ]
