# Generated by Django 5.2 on 2025-08-04 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zane_api",
            "0278_remove_previewenvtemplate_unique_template_name_per_project_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="previewenvtemplate",
            name="preview_env_limit",
            field=models.PositiveIntegerField(
                default=5, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
