# Generated by Django 5.2 on 2025-08-07 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0279_alter_previewenvtemplate_preview_env_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="previewenvmetadata",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preview_metas",
                to="zane_api.previewenvtemplate",
            ),
        ),
    ]
