# Generated by Django 5.2 on 2025-08-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0280_alter_previewenvmetadata_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="previewenvmetadata",
            name="auth_password",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="previewenvmetadata",
            name="auth_user",
            field=models.CharField(null=True),
        ),
    ]
