# Generated by Django 5.2 on 2025-08-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0281_previewenvmetadata_auth_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="previewenvmetadata",
            name="auth_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
