# Generated by Django 5.2 on 2025-08-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0282_previewenvmetadata_auth_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="previewenvtemplate",
            name="auth_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="previewenvtemplate",
            name="auth_password",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="previewenvtemplate",
            name="auth_user",
            field=models.CharField(null=True),
        ),
    ]
