# Generated by Django 5.2 on 2025-08-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0283_previewenvtemplate_auth_enabled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="previewenvmetadata",
            name="deploy_approved",
        ),
        migrations.AddField(
            model_name="previewenvmetadata",
            name="state",
            field=models.CharField(
                choices=[
                    ("APPROVED", "Approved"),
                    ("DECLINED", "Declined"),
                    ("PENDING", "Approval Required"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
