# Generated by Django 5.2 on 2025-08-24 21:57

import django.core.validators
import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0283_previewenvtemplate_auth_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIToken",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=11,
                        max_length=255,
                        prefix="tok_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for the token",
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(limit_value=1)
                        ],
                    ),
                ),
                ("token_hash", models.CharField(max_length=128, unique=True)),
                ("token_prefix", models.CharField(max_length=8)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("GUEST", "Guest"),
                            ("CONTRIBUTOR", "Contributor"),
                            ("MEMBER", "Member"),
                            ("ADMIN", "Admin"),
                            ("INSTANCE_OWNER", "Instance Owner"),
                        ],
                        default="CONTRIBUTOR",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "allowed_ips",
                    models.JSONField(
                        blank=True,
                        help_text="List of allowed IP addresses/CIDR blocks",
                        null=True,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to="zane_api.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["token_hash"], name="zane_api_ap_token_h_3f7734_idx"
                    ),
                    models.Index(
                        fields=["token_prefix"], name="zane_api_ap_token_p_676a20_idx"
                    ),
                    models.Index(
                        fields=["user"], name="zane_api_ap_user_id_465722_idx"
                    ),
                    models.Index(
                        fields=["project"], name="zane_api_ap_project_2e5c31_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="zane_api_ap_is_acti_cd27a4_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="zane_api_ap_expires_c24875_idx"
                    ),
                ],
                "unique_together": {("name", "project", "user")},
            },
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=11,
                        max_length=255,
                        prefix="mbr_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("GUEST", "Guest"),
                            ("CONTRIBUTOR", "Contributor"),
                            ("MEMBER", "Member"),
                            ("ADMIN", "Admin"),
                            ("INSTANCE_OWNER", "Instance Owner"),
                        ],
                        default="GUEST",
                        max_length=20,
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="zane_api.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user"], name="zane_api_pr_user_id_094ff7_idx"
                    ),
                    models.Index(
                        fields=["project"], name="zane_api_pr_project_d8c6c2_idx"
                    ),
                    models.Index(fields=["role"], name="zane_api_pr_role_517156_idx"),
                ],
                "unique_together": {("user", "project")},
            },
        ),
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=11,
                        max_length=255,
                        prefix="inv_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("GUEST", "Guest"),
                            ("CONTRIBUTOR", "Contributor"),
                            ("MEMBER", "Member"),
                            ("ADMIN", "Admin"),
                            ("INSTANCE_OWNER", "Instance Owner"),
                        ],
                        default="GUEST",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("token", models.CharField(max_length=64, unique=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="zane_api.project",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["email"], name="zane_api_us_email_eb08b0_idx"),
                    models.Index(
                        fields=["project"], name="zane_api_us_project_abadeb_idx"
                    ),
                    models.Index(
                        fields=["status"], name="zane_api_us_status_bbc643_idx"
                    ),
                    models.Index(fields=["token"], name="zane_api_us_token_9c03ce_idx"),
                    models.Index(
                        fields=["expires_at"], name="zane_api_us_expires_e8ad53_idx"
                    ),
                ],
                "unique_together": {("email", "project", "status")},
            },
        ),
    ]
