# Generated by Django 5.2 on 2025-08-23 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0284_remove_previewenvmetadata_deploy_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="previewenvmetadata",
            name="state",
            field=models.CharField(
                choices=[
                    ("APPROVED", "Approved"),
                    ("DECLINED", "Declined"),
                    ("PENDING", "Pending"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
