# Generated by Django 5.2 on 2025-08-23 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0285_alter_previewenvmetadata_state"),
    ]

    operations = [
        migrations.RenameField(
            model_name="previewenvmetadata",
            old_name="state",
            new_name="deploy_state",
        ),
    ]
