# Generated by Django 5.2 on 2025-08-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0285_auto_20250824_2157"),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='username',
            field=models.CharField(max_length=150, null=True, blank=True),
        ),
    ]
