# Generated by Django 5.2 on 2025-08-23 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0286_rename_state_previewenvmetadata_deploy_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="previewenvmetadata",
            name="pr_id",
        ),
        migrations.AddField(
            model_name="previewenvmetadata",
            name="pr_number",
            field=models.PositiveIntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
