# Generated by Django 5.2 on 2025-08-24 22:34

from django.db import migrations
from django.contrib.auth.models import User


def migrate_email_to_username(apps, schema_editor):
    """Migrate email data to username field"""
    UserInvitation = apps.get_model('zane_api', 'UserInvitation')
    User = apps.get_model('auth', 'User')
    
    print("Migrating invitation emails to usernames...")
    
    for invitation in UserInvitation.objects.all():
        # Try to find existing user with this email
        try:
            user = User.objects.get(email=invitation.email)
            invitation.username = user.username
            print(f"Found user: {invitation.email} → {user.username}")
        except User.DoesNotExist:
            # For non-accepted invitations, use part before @
            username_candidate = invitation.email.split('@')[0]
            invitation.username = username_candidate
            print(f"No user found: {invitation.email} → {username_candidate}")
        
        invitation.save()
    
    print(f"Migrated {UserInvitation.objects.count()} invitations")


def reverse_migration(apps, schema_editor):
    """Reverse migration - clear username field"""
    UserInvitation = apps.get_model('zane_api', 'UserInvitation')
    UserInvitation.objects.update(username=None)


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0286_auto_20250824_2233"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunPython(
            migrate_email_to_username,
            reverse_migration
        ),
    ]
