# Generated by Django 5.2 on 2025-08-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0287_auto_20250824_2234"),
    ]

    operations = [
        # First remove old unique constraint that includes email
        migrations.AlterUniqueTogether(
            name='userinvitation',
            unique_together=set(),
        ),
        # Make username non-nullable
        migrations.AlterField(
            model_name='userinvitation',
            name='username',
            field=models.CharField(max_length=150),
        ),
        # Remove the old email field
        migrations.RemoveField(
            model_name='userinvitation',
            name='email',
        ),
        # Add new unique constraint with username
        migrations.AlterUniqueTogether(
            name='userinvitation',
            unique_together={('username', 'project', 'status')},
        ),
    ]
