# Generated by Django 5.2 on 2025-08-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0287_remove_previewenvmetadata_pr_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="previewenvmetadata",
            name="pr_head_repo_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
