# Generated by Django 5.2 on 2025-08-26 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0288_auto_20250824_2237"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userinvitation",
            name="zane_api_us_email_eb08b0_idx",
        ),
        migrations.AlterField(
            model_name="userinvitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("DECLINED", "Declined"),
                    ("EXPIRED", "Expired"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="userinvitation",
            index=models.Index(
                fields=["username"], name="zane_api_us_usernam_37d9e4_idx"
            ),
        ),
    ]
