# Generated by Django 5.2 on 2025-08-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0288_previewenvmetadata_pr_head_repo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="previewenvmetadata",
            name="deploy_state",
            field=models.CharField(
                choices=[("APPROVED", "Approved"), ("PENDING", "Pending")],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
