# Generated by Django 5.2 on 2025-08-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0289_alter_previewenvmetadata_deploy_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="previewenvmetadata",
            name="pr_author",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
