# Generated by Django 5.2 on 2025-08-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0290_previewenvmetadata_pr_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="previewenvmetadata",
            old_name="pr_head_repo_url",
            new_name="pr_base_repo_url",
        ),
    ]
