# Generated by Django 5.2 on 2025-08-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zane_api",
            "0291_rename_pr_head_repo_url_previewenvmetadata_pr_base_repo_url",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="previewenvmetadata",
            old_name="repository_url",
            new_name="head_repository_url",
        ),
        migrations.AddField(
            model_name="previewenvmetadata",
            name="pr_base_branch_name",
            field=models.URLField(blank=True, null=True),
        ),
    ]
