# Generated by Django 5.2 on 2025-08-25 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zane_api",
            "0292_rename_repository_url_previewenvmetadata_head_repository_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="previewenvmetadata",
            name="pr_comment_id",
            field=models.PositiveBigIntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
