# Generated by Django 5.2 on 2025-08-29 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0293_previewenvmetadata_pr_comment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="previewenvmetadata",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preview_environments",
                to="zane_api.service",
            ),
            preserve_default=False,
        ),
    ]
