# Generated by Django 5.2 on 2025-10-11 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0295_containerregistry"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContainerRegistry",
            new_name="ContainerRegistryCredentials",
        ),
        migrations.AddField(
            model_name="service",
            name="container_registry_credentials",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="zane_api.containerregistrycredentials",
            ),
        ),
    ]
