# Generated by Django 5.2 on 2025-10-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "zane_api",
            "0296_rename_containerregistry_containerregistrycredentials_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerregistrycredentials",
            name="registry_type",
            field=models.CharField(
                choices=[
                    ("DOCKER_HUB", "Docker Hub"),
                    ("GITHUB", "GitHub Container Registry"),
                    ("GITLAB", "GitLab Container Registry"),
                    ("GOOGLE_ARTIFACT", "Google Artifact Registry"),
                    ("AWS_ECR", "AWS Elastic Container Registry"),
                    ("GENERIC", "Generic Docker Registry (v2 API)"),
                ],
                default="GENERIC",
                max_length=32,
            ),
        ),
    ]
