# Generated by Django 5.2 on 2025-10-11 18:53

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0003_initial"),
        ("zane_api", "0297_alter_containerregistrycredentials_registry_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="custom_build_registry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="container_registry.buildregistry",
            ),
        ),
        migrations.AlterField(
            model_name="containerregistrycredentials",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=20,
                max_length=255,
                prefix="reg_cred_",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
