# Generated by Django 5.2 on 2025-10-11 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0004_containerregistrycredentials_and_more"),
        ("zane_api", "0298_project_custom_build_registry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="container_registry_credentials",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="container_registry.containerregistrycredentials",
            ),
        ),
        migrations.DeleteModel(
            name="ContainerRegistryCredentials",
        ),
    ]
