# Generated by Django 5.2 on 2025-11-16 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0299_alter_service_container_registry_credentials_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="custom_build_registry",
        ),
    ]
