# Generated by Django 5.2 on 2025-11-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0300_remove_project_custom_build_registry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="slug",
            field=models.SlugField(max_length=38),
        ),
    ]
