# Generated by Django 5.2 on 2025-12-23 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0301_alter_service_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="volumes",
            field=models.ManyToManyField(related_name="services", to="zane_api.volume"),
        ),
        migrations.CreateModel(
            name="SharedVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("container_path", models.CharField(max_length=2048)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_volumes_owned",
                        to="zane_api.service",
                    ),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_volumes_reading",
                        to="zane_api.service",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zane_api.volume",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["container_path"], name="zane_api_sh_contain_46faa0_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("parent", models.F("reader")), _negated=True
                        ),
                        name="parent_cannot_be_reader",
                    ),
                    models.UniqueConstraint(
                        fields=("volume", "reader"), name="unique_reader_volume"
                    ),
                ],
            },
        ),
    ]
