# Generated by Django 5.2 on 2025-12-23 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0302_alter_service_volumes_sharedvolume"),
    ]

    operations = [
        migrations.AddField(
            model_name="volume",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volumes_new",
                to="zane_api.service",
            ),
        ),
    ]
