# Generated by Django 5.2 on 2025-12-23 18:07

from django.db import migrations


def migrate_m2m_to_fk(apps, schema_editor):
    """Migrate existing ManyToMany relationships to ForeignKey."""
    Volume = apps.get_model("zane_api", "Volume")
    Service = apps.get_model("zane_api", "Service")

    # For each volume, set service to the first (and should be only) related service
    for volume in Volume.objects.all():
        # Get services through M2M relationship
        services = Service.objects.filter(volumes=volume)
        first_service = services.first()

        if first_service:
            volume.service = first_service
            volume.save(update_fields=["service"])
        else:
            # Orphaned volume - delete it
            volume.delete()


def reverse_migration(apps, schema_editor):
    """Reverse the migration by copying FK back to M2M."""
    Volume = apps.get_model("zane_api", "Volume")

    # For each volume with a service FK, add it back to the M2M
    for volume in Volume.objects.filter(service__isnull=False):
        volume.service.volumes.add(volume)


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0303_volume_service"),
    ]

    operations = [
        migrations.RunPython(migrate_m2m_to_fk, reverse_code=reverse_migration),
    ]
