# Generated by Django 5.2 on 2025-12-23 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0305_alter_volume_service"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="volumes",
        ),
        migrations.AlterField(
            model_name="volume",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volumes",
                to="zane_api.service",
            ),
        ),
    ]
