# Generated by Django 5.2 on 2025-12-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0306_remove_service_volumes_alter_volume_service"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sharedvolume",
            name="parent_cannot_be_reader",
        ),
        migrations.RemoveField(
            model_name="sharedvolume",
            name="parent",
        ),
    ]
