# Generated by Django 5.2 on 2025-12-23 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0307_remove_sharedvolume_parent_cannot_be_reader_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedvolume",
            name="reader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_volumes",
                to="zane_api.service",
            ),
        ),
    ]
