# Generated by Django 5.2 on 2025-12-24 00:31

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0309_alter_deploymentchange_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharedvolume",
            name="id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet=None,
                length=11,
                max_length=255,
                prefix="shared_vol_",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
