# Generated by Django 5.2 on 2025-12-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0040_alter_buildregistry_name"),
        ("zane_api", "0311_alter_deploymentchange_field"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["deploy_token"], name="zane_api_se_deploy__9e359b_idx"
            ),
        ),
    ]
