# Generated by Django 5.2 on 2026-01-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0312_service_zane_api_se_deploy__9e359b_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="httplog",
            name="stack_id",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="httplog",
            name="stack_service_name",
            field=models.CharField(null=True),
        ),
    ]
