# Generated by Django 5.2 on 2026-01-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0313_httplog_stack_id_httplog_stack_service_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httplog",
            name="request_id",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
