# Generated by Django 5.2 on 2026-01-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0314_alter_httplog_request_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="httplog",
            name="zane_api_ht_request_a15dee_idx",
        ),
        migrations.RenameField(
            model_name="httplog",
            old_name="request_id",
            new_name="request_uuid",
        ),
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(
                fields=["request_uuid"], name="zane_api_ht_request_c84e20_idx"
            ),
        ),
    ]
