# Generated by Django 5.2 on 2026-01-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0315_remove_httplog_zane_api_ht_request_a15dee_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httplog",
            name="request_uuid",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
