# Generated by Django 5.2 on 2026-01-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0316_alter_httplog_request_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="httplog",
            name="registry_id",
            field=models.CharField(null=True),
        ),
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(
                fields=["registry_id"], name="zane_api_ht_registr_ac2455_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(
                fields=["stack_id"], name="zane_api_ht_stack_i_9ca17d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(
                fields=["stack_service_name"], name="zane_api_ht_stack_s_4e36cb_idx"
            ),
        ),
    ]
