# Generated by Django 5.2 on 2026-02-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compose", "0023_composestackdeployment_is_redeploy_of_and_more"),
        ("zane_api", "0317_httplog_registry_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="previewenvtemplate",
            name="stacks_to_clone",
            field=models.ManyToManyField(
                related_name="preview_templates", to="compose.composestack"
            ),
        ),
    ]
