# Generated by Django 5.2 on 2026-03-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zane_api", "0318_previewenvtemplate_stacks_to_clone"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="deploy_token",
            field=models.CharField(null=True),
        ),
    ]
