# Generated by Django 5.2 on 2026-05-12 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0319_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zane_api.workspace",
            ),
        ),
    ]
