# Generated by Django 5.2 on 2026-05-12 16:48

from django.db import migrations
from django.conf import settings


def create_default_workspace_and_attach_projects(apps, schema_editor):
    Workspace = apps.get_model("zane_api", "Workspace")
    Project = apps.get_model("zane_api", "Project")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)

    initial_user = (
        User.objects.filter(is_superuser=True).order_by("date_joined").first()
    )
    default_workspace = Workspace.objects.first()

    if initial_user is not None and default_workspace is None:
        default_workspace = Workspace.objects.create(name="Default workspace")
        Project.objects.update(workspace=default_workspace)


def rollback_workspace_and_projects(apps, schema_editor):
    Workspace = apps.get_model("zane_api", "Workspace")
    Project = apps.get_model("zane_api", "Project")

    Project.objects.update(workspace=None)
    Workspace.objects.filter().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("zane_api", "0320_project_workspace"),
    ]

    operations = [
        migrations.RunPython(
            create_default_workspace_and_attach_projects,
            reverse_code=rollback_workspace_and_projects,
        )
    ]
