# Generated by Django 5.2 on 2026-05-12 16:48

from django.db import migrations
from django.conf import settings


def create_default_workspace_and_attach_projects(apps, schema_editor):
    Workspace = apps.get_model("zane_api", "Workspace")
    Project = apps.get_model("zane_api", "Project")

    # Uses `app.get_model` to get the real auth user model
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)

    initial_user = User.objects.filter(is_superuser=True).earliest("date_joined")
    default_workspace = Workspace.objects.create(
        owner=initial_user, name="Default workspace"
    )

    Project.objects.update(workspace=default_workspace)


def rollback_workspace_and_projects(apps, schema_editor):
    Workspace = apps.get_model("zane_api", "Workspace")
    Project = apps.get_model("zane_api", "Project")

    Workspace.objects.filter().delete()
    Project.objects.update(workspace=None)


class Migration(migrations.Migration):
    dependencies = [
        ("zane_api", "0320_project_workspace"),
    ]

    operations = [
        migrations.RunPython(
            create_default_workspace_and_attach_projects,
            reverse_code=rollback_workspace_and_projects,
        )
    ]
