# Generated by Django 5.2 on 2026-05-12 16:48

from django.db import migrations


def create_default_workspace_and_attach_projects(apps, schema_editor):
    Workspace = apps.get_model("zane_api", "Workspace")
    Project = apps.get_model("zane_api", "Project")

    default_workspace = Workspace.objects.create(name="Default workspace")
    Project.objects.update(workspace=default_workspace)


def rollback_workspace_and_projects(apps, schema_editor):
    Workspace = apps.get_model("zane_api", "Workspace")
    Project = apps.get_model("zane_api", "Project")

    Workspace.objects.filter().delete()
    Project.objects.update(workspace=None)


class Migration(migrations.Migration):
    dependencies = [
        ("zane_api", "0320_project_workspace"),
    ]

    operations = [
        migrations.RunPython(
            create_default_workspace_and_attach_projects,
            reverse_code=rollback_workspace_and_projects,
        )
    ]
