# Generated by Django 5.2 on 2026-05-12 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zane_api", "0321_auto_20260512_1648"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="zane_api.workspace",
            ),
            preserve_default=False,
        ),
    ]
