# Generated by Django 5.2 on 2026-05-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0324_auto_20260512_1714"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacemembership",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Guest"), (2, "Contributor"), (3, "Member"), (4, "Admin")],
                default=3,
            ),
        ),
    ]
