# Generated by Django 5.2 on 2026-05-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0324_alter_workspacemembership_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspacemembership",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Guest"),
                    (2, "Contributor"),
                    (3, "Member"),
                    (4, "Admin"),
                    (5, "Owner"),
                ],
                default=3,
            ),
        ),
    ]
