# Generated by Django 5.2 on 2026-05-12 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0325_alter_workspacemembership_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="owner",
        ),
    ]
