# Generated by Django 5.2 on 2026-05-12 23:42

from django.db import migrations
from django.conf import settings


def create_default_workspace_membership(apps, schema_editor):
    Workspace = apps.get_model("zane_api", "Workspace")
    WorkspaceMembership = apps.get_model("zane_api", "WorkspaceMembership")

    default_workspace = Workspace.objects.first()

    # Uses `app.get_model` to get the real auth user model
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    initial_user = User.objects.filter(is_superuser=True).earliest("date_joined")

    WorkspaceMembership.objects.create(
        user=initial_user,
        workspace=default_workspace,
        role=5,  # OWNER
    )


def delete_all_workspace_memberships(apps, schema_editor):
    WorkspaceMembership = apps.get_model("zane_api", "WorkspaceMembership")
    WorkspaceMembership.objects.filter().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("zane_api", "0326_remove_workspace_owner"),
    ]

    operations = [
        migrations.RunPython(
            create_default_workspace_membership,
            reverse_code=delete_all_workspace_memberships,
        )
    ]
