# Generated by Django 5.2 on 2026-05-13 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0327_auto_20260512_2342"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="owner",
        ),
    ]
