# Generated by Django 5.2 on 2026-05-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0328_remove_project_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacemembership",
            name="accessible_projects",
            field=models.ManyToManyField(blank=True, to="zane_api.project"),
        ),
    ]
