# Generated by Django 5.2 on 2026-05-16 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0329_workspacemembership_accessible_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitapp",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="zane_api.workspace",
            ),
        ),
    ]
