# Generated by Django 5.2 on 2026-05-16 03:03

from django.db import migrations


def create_default_workspace_and_attach_gitapp(apps, schema_editor):
    Workspace = apps.get_model("zane_api", "Workspace")
    GitApp = apps.get_model("zane_api", "GitApp")

    default_workspace = Workspace.objects.earliest("created_at")
    GitApp.objects.update(workspace=default_workspace)


def rollback_workspace_and_gitapp(apps, schema_editor):
    GitApp = apps.get_model("zane_api", "GitApp")
    GitApp.objects.update(workspace=None)


class Migration(migrations.Migration):
    dependencies = [
        ("zane_api", "0330_gitapp_workspace"),
    ]

    operations = [
        migrations.RunPython(
            create_default_workspace_and_attach_gitapp,
            reverse_code=rollback_workspace_and_gitapp,
        )
    ]
