# Generated by Django 5.2 on 2026-05-16 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zane_api", "0331_auto_20260516_0303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gitapp",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="zane_api.workspace",
            ),
            preserve_default=False,
        ),
    ]
