# Generated by Django 5.2 on 2026-05-16 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0026_gitrepository_external_id"),
        ("zane_api", "0332_alter_gitapp_workspace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gitapp",
            name="github",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gitapp",
                to="git_connectors.githubapp",
            ),
        ),
        migrations.AlterField(
            model_name="gitapp",
            name="gitlab",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gitapp",
                to="git_connectors.gitlabapp",
            ),
        ),
    ]
