# Generated by Django 5.2 on 2026-05-17 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0333_alter_gitapp_github_alter_gitapp_gitlab"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archivedproject",
            name="owner",
        ),
    ]
