# Generated by Django 5.2 on 2026-05-30 15:14

import django.contrib.auth.validators
import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0334_remove_archivedproject_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceInvitation",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=11,
                        max_length=255,
                        prefix="wrk_ivt_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ]
                    ),
                ),
                ("token", models.CharField(max_length=35, unique=True)),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Guest"),
                            (2, "Contributor"),
                            (3, "Member"),
                            (4, "Admin"),
                            (5, "Owner"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "accessible_projects",
                    models.ManyToManyField(blank=True, to="zane_api.project"),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="zane_api.workspace",
                    ),
                ),
            ],
            options={
                "unique_together": {("username", "workspace")},
            },
        ),
    ]
