# Generated by Django 5.2 on 2026-05-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0335_workspaceinvitation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceinvitation",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "Guest"), (30, "Member"), (40, "Admin"), (50, "Owner")],
                default=30,
            ),
        ),
        migrations.AlterField(
            model_name="workspacemembership",
            name="role",
            field=models.PositiveSmallIntegerField(
                choices=[(10, "Guest"), (30, "Member"), (40, "Admin"), (50, "Owner")],
                default=30,
            ),
        ),
    ]
