# Generated by Django 5.2 on 2026-05-31 14:38

from django.db import migrations
from django.db.models import Case, When


def update_membership_role_values(apps, schema_editor):
    WorkspaceMembership = apps.get_model("zane_api", "WorkspaceMembership")
    WorkspaceMembership.objects.update(
        role=Case(
            When(role=1, then=10),  # Guest
            When(role=3, then=30),  # Member
            When(role=4, then=40),  # Admin
            When(role=5, then=50),  # Owner
            default=10,  # Guest
        )
    )


def rollback_membership_role_values(apps, schema_editor):
    WorkspaceMembership = apps.get_model("zane_api", "WorkspaceMembership")
    WorkspaceMembership.objects.update(
        role=Case(
            When(role=10, then=1),  # Guest
            When(role=30, then=3),  # Member
            When(role=40, then=4),  # Admin
            When(role=50, then=5),  # Owner
            default=1,  # Guest
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("zane_api", "0336_alter_workspaceinvitation_role_and_more"),
    ]

    operations = [
        migrations.RunPython(
            update_membership_role_values,
            reverse_code=rollback_membership_role_values,
        ),
    ]
