# Generated by Django 5.2 on 2026-06-05 23:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0337_auto_20260531_1438"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workspacemembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", 50)),
                fields=("workspace",),
                name="unique_owner_per_workspace",
            ),
        ),
    ]
