# Generated by Django 5.2 on 2026-06-07 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0338_workspacemembership_unique_owner_per_workspace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="zane_api.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="workspaceinvitation",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="zane_api.workspace",
            ),
        ),
    ]
