# Generated by Django 5.2 on 2026-07-11 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0340_workspaceinvitation_invited_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspacemembership",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="workspacemembership",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
