# Generated by Django 5.2 on 2026-08-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0342_alter_workspaceinvitation_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="httplog",
            name="request_country_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="httplog",
            name="source",
            field=models.CharField(
                choices=[
                    ("SERVICE", "Service"),
                    ("COMPOSE_STACK", "Compose stack"),
                    ("BUILD_REGISTRY", "Build registry"),
                    ("ZANE_OPS", "ZaneOps"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="SERVICE",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(fields=["source"], name="zane_api_ht_source_11f51a_idx"),
        ),
        migrations.AddIndex(
            model_name="httplog",
            index=models.Index(
                fields=["request_country_code"], name="zane_api_ht_request_c71358_idx"
            ),
        ),
    ]
