# Generated by Django 5.2 on 2026-08-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0344_auto_20260802_1535"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httplog",
            name="request_uuid",
            field=models.UUIDField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="httplog",
            name="source",
            field=models.CharField(
                choices=[
                    ("SERVICE", "Service"),
                    ("COMPOSE_STACK", "Compose stack"),
                    ("BUILD_REGISTRY", "Build registry"),
                    ("ZANE_OPS_API", "ZaneOps API"),
                    ("ZANE_OPS_FRONTEND", "ZaneOps Frontend"),
                    ("UNKNOWN", "Unknown"),
                ],
                default="SERVICE",
                max_length=20,
            ),
        ),
    ]
