# Generated by Django 5.2 on 2026-08-22 17:27

from django.db import migrations
from django.db.models import F


def fill_in_empty_request_uuid(apps, schema_editor):
    # we don't want to migrate data in tests because they are always done fresh
    HttpLog = apps.get_model("zane_api", "HttpLog")

    HttpLog.objects.filter(request_uuid__isnull=True).update(request_uuid=F("id"))


class Migration(migrations.Migration):
    dependencies = [
        ("zane_api", "0345_alter_httplog_request_uuid_alter_httplog_source"),
    ]

    operations = [
        migrations.RunPython(
            fill_in_empty_request_uuid,
        )
    ]
