# Generated by Django 5.2 on 2026-08-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zane_api", "0346_auto_20260822_1727"),
    ]

    operations = [
        migrations.AlterField(
            model_name="httplog",
            name="request_uuid",
            field=models.UUIDField(unique=True),
            preserve_default=False,
        ),
    ]
