# Generated by Django 5.2 on 2026-08-31 19:15

import django.contrib.postgres.fields
import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0347_alter_httplog_request_uuid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceApiToken",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=11,
                        max_length=255,
                        prefix="tok_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (10, "Viewer"),
                            (30, "Member"),
                            (40, "Admin"),
                            (50, "Owner"),
                        ]
                    ),
                ),
                (
                    "scopes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                (
                                    "deploy:write",
                                    "Trigger / cancel / redeploy deployments and previews",
                                ),
                                (
                                    "service:read",
                                    "Read service and compose-stack configuration",
                                ),
                                ("service:write", "Change services and compose stacks"),
                                ("env:read", "Read environment variables (sensitive)"),
                                ("env:write", "Change environment variables"),
                                (
                                    "logs:read",
                                    "Read runtime logs, build logs and metrics",
                                ),
                                (
                                    "project:read",
                                    "List and read projects and environments",
                                ),
                                ("project:write", "Change projects and environments"),
                            ],
                            max_length=255,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("last_four", models.CharField(max_length=4)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accessible_projects",
                    models.ManyToManyField(blank=True, to="zane_api.project"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to="zane_api.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
