# Generated by Django 5.2 on 2026-09-01 01:06

import zane_api.models.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0348_workspaceapitoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspaceapitoken",
            name="expires_at",
            field=models.DateTimeField(
                default=zane_api.models.main.default_api_token_expiry
            ),
        ),
    ]
