# Generated by Django 5.2 on 2026-09-09 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0349_alter_workspaceapitoken_expires_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspaceapitoken",
            name="revoked_at",
        ),
    ]
