# Generated by Django 5.2 on 2026-09-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0350_remove_workspace_api_token_revoked_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="urls",
            field=models.ManyToManyField(related_name="services", to="zane_api.url"),
        ),
    ]
