# Generated by Django 5.2 on 2026-09-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zane_api", "0351_alter_service_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="urls",
            field=models.ManyToManyField(to="zane_api.url"),
        ),
    ]
