# Generated by Django 5.2 on 2025-10-11 11:48

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContainerRegistry",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=14,
                        max_length=255,
                        prefix="cr_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField()),
                ("password", models.TextField()),
                ("username", models.CharField(max_length=1024, null=True)),
                (
                    "registry_type",
                    models.CharField(
                        choices=[
                            ("DOCKER_HUB", "Docker Hub"),
                            ("GITHUB", "GitHub Container Registry"),
                            ("GITLAB", "GitLab Container Registry"),
                            ("GENERIC", "Generic Docker Registry (v2 API)"),
                        ],
                        default="GENERIC",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
