# Generated by Django 5.2 on 2025-10-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContainerRegistry",
        ),
    ]
