# Generated by Django 5.2 on 2025-10-11 18:53

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("container_registry", "0002_delete_containerregistry"),
        ("zane_api", "0297_alter_containerregistrycredentials_registry_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="S3Credentials",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=11,
                        max_length=14,
                        prefix="s3_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bucket", models.CharField(max_length=255)),
                ("region", models.CharField(default="us-east-1", max_length=100)),
                ("access_key", models.CharField(max_length=255)),
                ("secret_key", models.CharField(max_length=255)),
                ("endpoint_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BuildRegistry",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=20,
                        max_length=30,
                        prefix="build_reg_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_managed", models.BooleanField(default=True)),
                ("is_global", models.BooleanField(default=False)),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[("LOCAL", "Local Disk"), ("S3", "Amazon S3")],
                        default="LOCAL",
                        max_length=50,
                    ),
                ),
                ("supports_multiarch", models.BooleanField(default=False)),
                (
                    "external_registry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="build_registries",
                        to="zane_api.containerregistrycredentials",
                    ),
                ),
                (
                    "s3_credentials",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="container_registry.s3credentials",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_global", True)),
                        fields=("is_global",),
                        name="unique_global_registry_per_instance",
                    )
                ],
            },
        ),
    ]
