# Generated by Django 5.2 on 2025-10-11 18:58

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerRegistryCredentials",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=20,
                        max_length=255,
                        prefix="reg_cred_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField()),
                ("password", models.TextField()),
                ("username", models.CharField(max_length=1024, null=True)),
                (
                    "registry_type",
                    models.CharField(
                        choices=[
                            ("DOCKER_HUB", "Docker Hub"),
                            ("GITHUB", "GitHub Container Registry"),
                            ("GITLAB", "GitLab Container Registry"),
                            ("GOOGLE_ARTIFACT", "Google Artifact Registry"),
                            ("AWS_ECR", "AWS Elastic Container Registry"),
                            ("GENERIC", "Generic Docker Registry (v2 API)"),
                        ],
                        default="GENERIC",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="buildregistry",
            name="external_registry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="build_registries",
                to="container_registry.containerregistrycredentials",
            ),
        ),
    ]
