# Generated by Django 5.2 on 2025-10-12 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0004_containerregistrycredentials_and_more"),
        ("s3_targets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildregistry",
            name="s3_credentials",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="s3_targets.s3credentials",
            ),
        ),
        migrations.DeleteModel(
            name="S3Credentials",
        ),
    ]
