# Generated by Django 5.2 on 2025-10-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0005_alter_buildregistry_s3_credentials_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerregistrycredentials",
            name="password",
            field=models.TextField(null=True),
        ),
    ]
