# Generated by Django 5.2 on 2025-10-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0006_alter_containerregistrycredentials_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerregistrycredentials",
            name="password",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="containerregistrycredentials",
            name="username",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
