# Generated by Django 5.2 on 2025-11-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "container_registry",
            "0007_alter_containerregistrycredentials_password_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="containerregistrycredentials",
            unique_together={("url", "username")},
        ),
    ]
