# Generated by Django 5.2 on 2025-11-01 18:46

import container_registry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "container_registry",
            "0007_alter_containerregistrycredentials_password_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="containerregistrycredentials",
            name="name",
            field=models.CharField(
                default=container_registry.models.generate_registry_name,
                max_length=1024,
            ),
        ),
    ]
