# Generated by Django 5.2 on 2025-11-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "container_registry",
            "0008_alter_containerregistrycredentials_unique_together",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="containerregistrycredentials",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="containerregistrycredentials",
            constraint=models.UniqueConstraint(
                condition=models.Q(("username__isnull", False)),
                fields=("url", "username"),
                name="unique_url_username_when_not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="containerregistrycredentials",
            constraint=models.UniqueConstraint(
                condition=models.Q(("username__isnull", True)),
                fields=("url",),
                name="unique_url_when_username_null",
            ),
        ),
    ]
