# Generated by Django 5.2 on 2025-11-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "container_registry",
            "0009_alter_containerregistrycredentials_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="containerregistrycredentials",
            options={"ordering": ("-created_at",)},
        ),
    ]
