# Generated by Django 5.2 on 2025-11-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0010_alter_containerregistrycredentials_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="containerregistrycredentials",
            options={"ordering": ("created_at",)},
        ),
    ]
