# Generated by Django 5.2 on 2025-11-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0011_alter_containerregistrycredentials_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="containerregistrycredentials",
            name="unique_url_username_when_not_null",
        ),
        migrations.RemoveConstraint(
            model_name="containerregistrycredentials",
            name="unique_url_when_username_null",
        ),
        migrations.AddField(
            model_name="containerregistrycredentials",
            name="name",
            field=models.CharField(blank=True, null=True),
        ),
    ]
