# Generated by Django 5.2 on 2025-11-08 20:49

from django.db import migrations
from faker import Faker
import time


def populate_default_name(apps, schema_editor):
    fake = Faker()
    Faker.seed(time.monotonic())

    ContainerRegistryCredentials = apps.get_model(
        "container_registry", "ContainerRegistryCredentials"
    )

    for credentials in ContainerRegistryCredentials.objects.all():
        credentials.name = fake.slug()
        credentials.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "container_registry",
            "0012_remove_containerregistrycredentials_unique_url_username_when_not_null_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            populate_default_name,
        ),
    ]
