# Generated by Django 5.2 on 2025-11-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container_registry", "0013_auto_20251108_2049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerregistrycredentials",
            name="name",
            field=models.SlugField(unique=True),
            preserve_default=False,
        ),
    ]
