# Generated by Django 5.2 on 2025-11-08 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0014_alter_containerregistrycredentials_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="containerregistrycredentials",
            old_name="name",
            new_name="slug",
        ),
    ]
