# Generated by Django 5.2 on 2025-11-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container_registry", "0015_rename_name_containerregistrycredentials_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containerregistrycredentials",
            name="password",
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="containerregistrycredentials",
            name="username",
            field=models.CharField(max_length=1024),
            preserve_default=False,
        ),
    ]
