# Generated by Django 5.2 on 2025-11-17 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "container_registry",
            "0016_alter_containerregistrycredentials_password_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buildregistry",
            name="supports_multiarch",
        ),
    ]
