# Generated by Django 5.2 on 2025-11-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0018_alter_buildregistry_external_registry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildregistry",
            name="is_global",
            field=models.BooleanField(default=True),
        ),
    ]
