# Generated by Django 5.2 on 2025-11-17 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0019_alter_buildregistry_is_global"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buildregistry",
            old_name="external_registry",
            new_name="external_credentials",
        ),
    ]
