# Generated by Django 5.2 on 2025-11-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "container_registry",
            "0020_rename_external_registry_buildregistry_external_credentials",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="containerregistrycredentials",
            index=models.Index(
                fields=["registry_type"], name="container_r_registr_1f51ee_idx"
            ),
        ),
    ]
