# Generated by Django 5.2 on 2025-11-17 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "container_registry",
            "0021_containerregistrycredentials_container_r_registr_1f51ee_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildregistry",
            name="external_credentials",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="build_registries",
                to="container_registry.containerregistrycredentials",
            ),
        ),
    ]
