# Generated by Django 5.2 on 2025-11-21 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container_registry", "0022_alter_buildregistry_external_credentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildregistry",
            name="external_credentials",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="build_registries",
                to="container_registry.containerregistrycredentials",
            ),
            preserve_default=False,
        ),
    ]
