# Generated by Django 5.2 on 2025-11-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container_registry", "0023_alter_buildregistry_external_credentials"),
        ("zane_api", "0300_remove_project_custom_build_registry"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContainerRegistryCredentials",
            new_name="SharedRegistryCredentials",
        ),
        migrations.RenameIndex(  # type: ignore
            model_name="sharedregistrycredentials",
            new_name="container_r_registr_d44df2_idx",
            old_name="container_r_registr_1f51ee_idx",
        ),
        migrations.RemoveField(
            model_name="buildregistry",
            name="external_credentials",
        ),
        migrations.AddField(
            model_name="buildregistry",
            name="registry_password",
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buildregistry",
            name="registry_url",
            field=models.URLField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="buildregistry",
            name="registry_username",
            field=models.CharField(max_length=1024),
            preserve_default=False,
        ),
    ]
