# Generated by Django 5.2 on 2025-11-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "container_registry",
            "0024_rename_containerregistrycredentials_sharedregistrycredentials_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="buildregistry",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
