# Generated by Django 5.2 on 2025-11-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0025_buildregistry_version"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buildregistry",
            old_name="registry_url",
            new_name="registry_domain",
        ),
    ]
