# Generated by Django 5.2 on 2025-11-21 10:22

import zane_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "container_registry",
            "0026_rename_registry_url_buildregistry_registry_domain",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildregistry",
            name="registry_domain",
            field=models.CharField(
                max_length=2048, validators=[zane_api.validators.validate_url_domain]
            ),
        ),
    ]
