# Generated by Django 5.2 on 2025-11-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0027_alter_buildregistry_registry_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildregistry",
            name="service_alias",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="buildregistry",
            name="swarm_service_name",
            field=models.CharField(null=True),
        ),
    ]
