# Generated by Django 5.2 on 2025-11-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0028_buildregistry_service_alias_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buildregistry",
            name="s3_credentials",
        ),
        migrations.AddField(
            model_name="buildregistry",
            name="s3_access_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="buildregistry",
            name="s3_bucket",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="buildregistry",
            name="s3_encrypt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="buildregistry",
            name="s3_endpoint",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="buildregistry",
            name="s3_region",
            field=models.CharField(blank=True, default="us-east-1", max_length=50),
        ),
        migrations.AddField(
            model_name="buildregistry",
            name="s3_secret_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="buildregistry",
            name="s3_secure",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="buildregistry",
            name="storage_backend",
            field=models.CharField(
                choices=[("LOCAL", "Local Disk"), ("S3", "S3")],
                default="LOCAL",
                max_length=50,
            ),
        ),
    ]
