# Generated by Django 5.2 on 2025-11-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0029_remove_buildregistry_s3_credentials_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildregistry",
            name="is_secure",
            field=models.BooleanField(default=True),
        ),
    ]
