# Generated by Django 5.2 on 2025-11-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0030_buildregistry_is_secure"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buildregistry",
            name="is_managed",
        ),
    ]
