# Generated by Django 5.2 on 2025-11-23 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0031_remove_buildregistry_is_managed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buildregistry",
            name="s3_encrypt",
        ),
    ]
