# Generated by Django 5.2 on 2025-11-23 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0032_remove_buildregistry_s3_encrypt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buildregistry",
            name="s3_access_key",
        ),
        migrations.RemoveField(
            model_name="buildregistry",
            name="s3_bucket",
        ),
        migrations.RemoveField(
            model_name="buildregistry",
            name="s3_endpoint",
        ),
        migrations.RemoveField(
            model_name="buildregistry",
            name="s3_region",
        ),
        migrations.RemoveField(
            model_name="buildregistry",
            name="s3_secret_key",
        ),
        migrations.RemoveField(
            model_name="buildregistry",
            name="s3_secure",
        ),
        migrations.AddField(
            model_name="buildregistry",
            name="s3_credentials",
            field=models.JSONField(null=True),
        ),
    ]
