# Generated by Django 5.2 on 2025-11-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0033_remove_buildregistry_s3_access_key_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="buildregistry",
            index=models.Index(
                fields=["registry_domain"], name="container_r_registr_3d86a9_idx"
            ),
        ),
    ]
