# Generated by Django 5.2 on 2025-11-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0034_buildregistry_container_r_registr_3d86a9_idx"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="buildregistry",
            name="unique_global_registry_per_instance",
        ),
        migrations.RenameField(
            model_name="buildregistry",
            old_name="is_global",
            new_name="is_default",
        ),
        migrations.AddConstraint(
            model_name="buildregistry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="unique_global_registry_per_instance",
            ),
        ),
    ]
