# Generated by Django 5.2 on 2025-11-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "container_registry",
            "0035_remove_buildregistry_unique_global_registry_per_instance_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buildregistry",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="sharedregistrycredentials",
            options={"ordering": ["created_at"]},
        ),
    ]
