# Generated by Django 5.2 on 2025-11-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0036_alter_buildregistry_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildregistry",
            name="deployment_status",
            field=models.CharField(
                choices=[
                    ("PREPARING", "Preparing"),
                    ("STARTING", "Starting"),
                    ("RESTARTING", "Restarting"),
                    ("HEALTHY", "Healthy"),
                    ("UNHEALTHY", "Unhealthy"),
                ],
                default="PREPARING",
                max_length=50,
            ),
        ),
    ]
