# Generated by Django 5.2 on 2025-11-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0037_buildregistry_deployment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildregistry",
            name="deployment_status_reason",
            field=models.TextField(default="preparing"),
        ),
    ]
