# Generated by Django 5.2 on 2025-11-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0038_buildregistry_deployment_status_reason"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buildregistry",
            old_name="deployment_status",
            new_name="health_status",
        ),
        migrations.RenameField(
            model_name="buildregistry",
            old_name="deployment_status_reason",
            new_name="healthcheck_message",
        ),
    ]
