# Generated by Django 5.2 on 2025-12-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "container_registry",
            "0039_rename_deployment_status_buildregistry_health_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildregistry",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
