# Generated by Django 5.2 on 2026-05-16 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0040_alter_buildregistry_name"),
        ("zane_api", "0333_alter_gitapp_github_alter_gitapp_gitlab"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildregistry",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="build_registries",
                to="zane_api.workspace",
            ),
        ),
        migrations.AddField(
            model_name="sharedregistrycredentials",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_credentials",
                to="zane_api.workspace",
            ),
        ),
    ]
