# Generated by Django 5.2 on 2026-05-16 04:05

from django.db import migrations


def create_default_workspace_and_attach_registries(apps, schema_editor):
    Workspace = apps.get_model("zane_api", "Workspace")
    SharedRegistryCredentials = apps.get_model(
        "container_registry", "SharedRegistryCredentials"
    )
    BuildRegistry = apps.get_model("container_registry", "BuildRegistry")

    default_workspace = Workspace.objects.earliest("created_at")
    SharedRegistryCredentials.objects.update(workspace=default_workspace)
    BuildRegistry.objects.update(workspace=default_workspace)


def rollback_workspace_and_registries(apps, schema_editor):
    SharedRegistryCredentials = apps.get_model(
        "container_registry", "SharedRegistryCredentials"
    )
    BuildRegistry = apps.get_model("container_registry", "BuildRegistry")

    SharedRegistryCredentials.objects.update(workspace=None)
    BuildRegistry.objects.update(workspace=None)


class Migration(migrations.Migration):
    dependencies = [
        ("container_registry", "0041_buildregistry_workspace_and_more"),
    ]

    operations = [
        migrations.RunPython(
            create_default_workspace_and_attach_registries,
            reverse_code=rollback_workspace_and_registries,
        )
    ]
