# Generated by Django 5.2 on 2026-05-16 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("container_registry", "0042_auto_20260516_0405"),
        ("zane_api", "0333_alter_gitapp_github_alter_gitapp_gitlab"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildregistry",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="build_registries",
                to="zane_api.workspace",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sharedregistrycredentials",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_credentials",
                to="zane_api.workspace",
            ),
            preserve_default=False,
        ),
    ]
