# Generated by Django 5.2 on 2026-05-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("container_registry", "0043_alter_buildregistry_workspace_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buildregistry",
            name="workspace",
        ),
    ]
