# Generated by Django 5.2 on 2025-07-03 14:03

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GitRepository",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=14,
                        max_length=255,
                        prefix="repo_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner", models.SlugField(max_length=255)),
                ("repo", models.SlugField(max_length=255)),
                ("url", models.URLField(unique=True)),
                ("private", models.BooleanField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GitlabApp",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=14,
                        max_length=255,
                        prefix="gl_app_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=255)),
                ("gitlab_url", models.URLField(default="https://gitlab.com")),
                ("app_id", models.CharField(max_length=255, null=True)),
                ("redirect_uri", models.URLField(max_length=255, null=True)),
                ("secret", models.TextField(null=True)),
                ("access_token", models.TextField(null=True)),
                ("refresh_token", models.TextField(null=True)),
                ("group_name", models.CharField(max_length=2000, null=True)),
                ("expires_at", models.PositiveBigIntegerField(null=True)),
                (
                    "repositories",
                    models.ManyToManyField(to="git_connectors.gitrepository"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GithubApp",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=14,
                        max_length=255,
                        prefix="gh_app_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("installation_id", models.CharField(max_length=255, null=True)),
                ("app_url", models.URLField(max_length=255)),
                ("client_id", models.CharField(max_length=255)),
                ("app_id", models.PositiveIntegerField(unique=True)),
                ("client_secret", models.TextField()),
                ("webhook_secret", models.TextField()),
                ("private_key", models.TextField()),
                (
                    "repositories",
                    models.ManyToManyField(to="git_connectors.gitrepository"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
