# Generated by Django 5.2 on 2025-07-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubapp",
            name="repositories",
            field=models.ManyToManyField(
                related_name="githubapps", to="git_connectors.gitrepository"
            ),
        ),
    ]
