# Generated by Django 5.2 on 2025-07-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0002_alter_githubapp_repositories"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="gitrepository",
            index=models.Index(fields=["owner"], name="git_connect_owner_a77dd6_idx"),
        ),
        migrations.AddIndex(
            model_name="gitrepository",
            index=models.Index(fields=["repo"], name="git_connect_repo_419d74_idx"),
        ),
    ]
