# Generated by Django 5.2 on 2025-07-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0003_gitrepository_git_connect_owner_a77dd6_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="gitrepository",
            name="git_connect_owner_a77dd6_idx",
        ),
        migrations.RemoveIndex(
            model_name="gitrepository",
            name="git_connect_repo_419d74_idx",
        ),
        migrations.AddIndex(
            model_name="gitrepository",
            index=models.Index(
                models.Func(models.F("owner"), function="LOWER"),
                name="owner_istartswith_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gitrepository",
            index=models.Index(
                models.Func(models.F("repo"), function="LOWER"),
                name="repo_istartswith_idx",
            ),
        ),
    ]
