# Generated by Django 5.2 on 2025-07-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0005_remove_gitrepository_owner_istartswith_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubapp",
            name="installation_id",
            field=models.PositiveIntegerField(max_length=255, null=True),
        ),
    ]
