# Generated by Django 5.2 on 2025-07-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0006_alter_githubapp_installation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubapp",
            name="installation_id",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
