# Generated by Django 5.2 on 2025-07-06 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0007_alter_githubapp_installation_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gitlabapp",
            name="access_token",
        ),
    ]
