# Generated by Django 5.2 on 2025-07-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0008_remove_gitlabapp_access_token"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gitlabapp",
            old_name="slug",
            new_name="name",
        ),
    ]
