# Generated by Django 5.2 on 2025-07-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0009_rename_slug_gitlabapp_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gitlabapp",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
