# Generated by Django 5.2 on 2025-07-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0010_alter_gitlabapp_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gitlabapp",
            name="expires_at",
        ),
        migrations.AlterField(
            model_name="gitlabapp",
            name="app_id",
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gitlabapp",
            name="redirect_uri",
            field=models.URLField(max_length=255),
            preserve_default=False,
        ),
    ]
