# Generated by Django 5.2 on 2025-07-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "git_connectors",
            "0011_remove_gitlabapp_expires_at_alter_gitlabapp_app_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="gitlabapp",
            name="secret",
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
