# Generated by Django 5.2 on 2025-07-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0012_alter_gitlabapp_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gitlabapp",
            name="refresh_token",
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
