# Generated by Django 5.2 on 2025-07-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0013_alter_gitlabapp_refresh_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gitlabapp",
            name="redirect_uri",
        ),
    ]
