# Generated by Django 5.2 on 2025-07-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0014_remove_gitlabapp_redirect_uri"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gitlabapp",
            name="group_name",
        ),
    ]
