# Generated by Django 5.2 on 2025-07-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0015_remove_gitlabapp_group_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitlabapp",
            name="redirect_uri",
            field=models.URLField(
                default="https://127-0-0-1.sslip.io/api/connectors/gitlab/setup"
            ),
        ),
    ]
