# Generated by Django 5.2 on 2025-07-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0016_gitlabapp_redirect_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitrepository",
            name="path",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
