# Generated by Django 5.2 on 2025-07-07 01:57

from django.db import migrations, models
from django.db.models import F, Func, Value


def clear_git_repository_path(apps, schema_editor):
    GitRepository = apps.get_model("git_connectors", "GitRepository")
    GitRepository.objects.update(path="")


def populate_git_repository_path(apps, schema_editor):
    GitRepository = apps.get_model("git_connectors", "GitRepository")

    GitRepository.objects.filter().update(
        path=Func(
            F("owner"),
            Value("/"),
            F("repo"),
            function="concat",
            output_field=models.CharField(),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0017_gitrepository_path"),
    ]

    operations = [
        migrations.RunPython(
            populate_git_repository_path,
            reverse_code=clear_git_repository_path,
        ),
    ]
