# Generated by Django 5.2 on 2025-07-07 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0018_auto_20250707_0157"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="gitrepository",
            name="owner_istartswith_idx",
        ),
        migrations.RemoveIndex(
            model_name="gitrepository",
            name="repo_istartswith_idx",
        ),
        migrations.RemoveField(
            model_name="gitrepository",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="gitrepository",
            name="repo",
        ),
    ]
