# Generated by Django 5.2 on 2025-07-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0019_remove_gitrepository_owner_istartswith_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubapp",
            name="repositories",
            field=models.ManyToManyField(
                related_name="githubapp", to="git_connectors.gitrepository"
            ),
        ),
        migrations.AlterField(
            model_name="gitlabapp",
            name="repositories",
            field=models.ManyToManyField(
                related_name="gitlabapp", to="git_connectors.gitrepository"
            ),
        ),
    ]
