# Generated by Django 5.2 on 2025-07-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0021_alter_githubapp_repositories_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="githubapp",
            index=models.Index(
                fields=["installation_id"], name="git_connect_install_8c6a09_idx"
            ),
        ),
    ]
