# Generated by Django 5.2 on 2025-07-11 17:18

from django.db import migrations, models
from django.db.models import F, Func, Value


def remove_git_suffix_to_repository_url(apps, schema_editor):
    GitRepository = apps.get_model("git_connectors", "GitRepository")
    GitRepository.objects.filter().update(
        url=Func(
            F("url"),
            Value(r"\.git$"),
            Value(""),
            function="REGEXP_REPLACE",
        )
    )


def add_git_suffix_to_repository_urls(apps, schema_editor):
    GitRepository = apps.get_model("git_connectors", "GitRepository")

    GitRepository.objects.filter().update(
        url=Func(
            F("url"),
            Value(".git"),
            function="concat",
            output_field=models.CharField(),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0022_githubapp_git_connect_install_8c6a09_idx"),
    ]

    operations = [
        migrations.RunPython(
            add_git_suffix_to_repository_urls,
            reverse_code=remove_git_suffix_to_repository_url,
        ),
    ]
