# Generated by Django 5.2 on 2025-07-14 01:56

import git_connectors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0023_auto_20250711_1718"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitlabapp",
            name="webhook_secret",
            field=models.CharField(
                default=git_connectors.models.get_default_webhook_secret, max_length=65
            ),
        ),
        migrations.AlterField(
            model_name="gitlabapp",
            name="redirect_uri",
            field=models.URLField(
                default=git_connectors.models.get_default_redirect_uri
            ),
        ),
    ]
