# Generated by Django 5.2 on 2025-07-14 02:40

import git_connectors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0024_gitlabapp_webhook_secret_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gitlabapp",
            name="webhook_secret",
            field=models.CharField(
                default=git_connectors.models.get_default_webhook_secret,
                max_length=65,
                unique=True,
            ),
        ),
    ]
