# Generated by Django 5.2 on 2025-09-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_connectors", "0025_alter_gitlabapp_webhook_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitrepository",
            name="external_id",
            field=models.CharField(null=True),
        ),
    ]
