# Generated by Django 5.2 on 2025-05-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webshell", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sshkey",
            old_name="key",
            new_name="public_key",
        ),
        migrations.AddField(
            model_name="sshkey",
            name="private_key",
            field=models.TextField(unique=True),
            preserve_default=False,
        ),
    ]
