# Generated by Django 5.2 on 2025-05-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webshell", "0002_rename_key_sshkey_public_key_sshkey_private_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sshkey",
            name="private_key",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="sshkey",
            name="public_key",
            field=models.TextField(),
        ),
    ]
