# Generated by Django 5.2 on 2025-05-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webshell", "0003_alter_sshkey_private_key_alter_sshkey_public_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sshkey",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
