# Generated by Django 5.2 on 2025-05-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webshell", "0004_alter_sshkey_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sshkey",
            name="name",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
