# Generated by Django 5.2 on 2025-05-11 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webshell", "0005_alter_sshkey_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sshkey",
            old_name="name",
            new_name="slug",
        ),
    ]
