# Generated by Django 5.2 on 2025-05-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webshell", "0006_rename_name_sshkey_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="sshkey",
            name="fingerprint",
            field=models.CharField(default=None, null=True),
        ),
    ]
