# Generated by Django 5.2 on 2025-10-12 14:38
import base64
import hashlib

from django.db import migrations
from django.conf import settings


def generate_fingerprint(public_key: str) -> str:
    # Read the OpenSSH‐formatted public key and extract the Base64 blob
    key_blob = public_key.strip().split()[1]

    # Decode the blob, hash it with SHA-256, then Base64-encode without padding
    blob = base64.b64decode(key_blob)
    digest = hashlib.sha256(blob).digest()
    fingerprint = base64.b64encode(digest).rstrip(b"=").decode("ascii")

    return f"SHA256:{fingerprint}"


def create_ssh_key_fingerprint(apps, schema_editor):
    # we don't want to migrate data in tests because they are always done fresh
    SSHKey = apps.get_model("webshell", "SSHKey")

    # Clear the content_text field (or set to None)
    for key in SSHKey.objects.filter(fingerprint__isnull=True).all():
        key.fingerprint = generate_fingerprint(key.public_key)
        key.save()


class Migration(migrations.Migration):
    dependencies = [
        ("webshell", "0007_sshkey_fingerprint"),
    ]

    operations = [
        migrations.RunPython(
            create_ssh_key_fingerprint,
        ),
    ]
