# Generated by Django 5.2 on 2026-09-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webshell", "0008_auto_20251012_1438"),
    ]

    operations = [
        migrations.AddField(
            model_name="sshkey",
            name="port",
            field=models.PositiveIntegerField(default=22),
        ),
    ]
