# Generated by Django 5.2 on 2026-09-23 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webshell", "0009_sshkey_port"),
        ("swarm", "0014_remove_swarmnode_ssh_keys_alter_sshkey_node"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SSHKey",
        ),
    ]
