name: Biome Check Formatting
on:
  pull_request:

concurrency:
  group: ${{ github.ref }}-format
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }} # cancel in progress on push (only if not on `main`)

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.9.4
      - name: Run Biome
        run: biome check .
