# Generated by Django 5.2 on 2025-10-12 23:30

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="S3Credentials",
            fields=[
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        length=11,
                        max_length=14,
                        prefix="s3_",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bucket", models.CharField(max_length=255)),
                ("region", models.CharField(default="us-east-1", max_length=100)),
                ("access_key", models.CharField(max_length=255)),
                ("secret_key", models.CharField(max_length=255)),
                ("endpoint_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
