# Generated by Django 5.2 on 2026-05-16 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("s3_targets", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="S3Credentials",
        ),
    ]
